### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Carbon-Ghost** [gigabit101/QuantumStorage#10]
I don't understand the changes in this update, first why did you made it require RebornCore ? Second why MKx, I mean we simply wanted DSU xD ? 2.5 Will it be configurable ?

**Comment by gigabit101** [comment]
There will be configs to disable these soon.
I am working on adding more things into this mod eg: the bags and so on.
As for RebornCore I am using allot of the same code from the QuantumChests in TechReborn so this made it simple for me to work on both at the same time.
You have seen all to configs in TechReborn so it will all be configurable as soon as I get the next release out atm I'm releasing betas.

**Comment by gigabit101** [comment]
ps @Carbon-Ghost if u have question IRC Techreborn channel

**Comment by Carbon-Ghost** [comment]
oh kk, and yeah haven't used IRC for a long time now... lol, thanks ;)
