### ISSUE TITLE
[1.12] Quantum Barrel + Refined Storage - External Bus Weirdness

### ISSUE THREAD

**Issue by llloyd4** [gigabit101/QuantumStorage#100]
So, I put an External Bus from Refined Storage onto the Quantum Barrel and it's reading 128/64 items. Having the same issue with Yabba barrels. Though Drawers it displays right. So... O.o

Quantum Storage 1.12-4.4.0
Refined Storage 1.5.16

**Comment by gigabit101** [comment]
This should only be a gui issue and should work fine.

**Comment by ExDomino** [comment]
Quantum Barrel sends as information that it only has 1 slot on it.
Also, it ceasses to input items from its sides when it reachs exactly 4096 items on it, even if right click still allows to put more items, its automatic input is however disabled.

**Comment by llloyd4** [comment]
Right and Storage Drawers shows just fine so I don't know how they do it. I
was more worried about crashing  I was using Yabba barrels and had a
mysterious crash randomly when opening the RS grid that went away when I
switched to QS barrels. But the error report kept pointing to RS. >.<

**Comment by llloyd4** [comment]
Oh! Might I suggest upgrades, like Drawers, to increase that 2k? Had one
hell of a mess when my quarry filled them and the RS disks up. >.<

**Comment by gigabit101** [comment]
The barrels will be being removed as of next version as I dont like the feel of them in this mod,
I will be leaving them in and for now I have removed the recipe
