### ISSUE TITLE
Quantum Barrel piped input limited to 4096 items

### ISSUE THREAD

**Issue by ouroborus** [gigabit101/QuantumStorage#105]
Mentioned [here](https://github.com/gigabit101/QuantumStorage/issues/100#issuecomment-322014293) but I thought I'd break it out into a separate issue.

Piped input (I tested with Mekanism's Logistical Transporters and Applied Energistics 2's ME Storage Bus) attached to the Quantum Barrel seems limited to 4096.

Manual input doesn't appear to have this limit.

Devices like the Mechanical User (Extra Utilities 2; Activate Block With Item, Right Click, Random Slot) can put items into a quantum barrel beyond this 4096 limit.

**Comment by gigabit101** [comment]
The barrels will be being removed as of next version as I dont like the feel of them in this mod,
I will be leaving them in and for now I have removed the recipe
