### ISSUE TITLE
[1.12.1] Minecraft refuses to launch because of MC version

### ISSUE THREAD

**Issue by Peca21** [gigabit101/QuantumStorage#108]
Quantum storage has 1.12.1 as the compatible version on curse but 1.12.1 minecraft refuses to launch because it requires 1.12.2.

https://i.imgur.com/iekPjfu.png

QuantumStorage-1.12-4.4.1

**Comment by YOYOK9** [comment]
I can confirm, having the same issue as well:
https://puu.sh/xTjXs/27ddb43483.png

QuantumStorage: 1.12-4.4.1
Minecraft client: 1.12.1

**Comment by gigabit101** [comment]
Fixed in 4.4.2
