### ISSUE TITLE
Game/World Crash - QuantumTank on SawMill Thermal Expansion

### ISSUE THREAD

**Issue by cl3w** [gigabit101/QuantumStorage#116]
Hello,
Versions:
Minecraft 1.12.1 forge-14.22.1.2485
QuantumStorage-1.12-4.4.3
ThermalExpansion-1.12-5.3.6.20-universal

When placing a QuantumTank on a Thermal Expansion SawMill to fill the QuantumTank with the liquid "Sap" from Thermal Expansion Sawmill it will crash the game and the world later on
After that u no longer can join the world because at starting loading your world, the game crashes

Repreduceable:

-place an upgraded version of the Thermal Expansion Sawmill with the augment: "Resin Funnel" and saw wood now it will produce the liquid "Sap" as a side product. Set the topside of the Sawmill to as an output

- Place a Quantum Tank for storing the Liquid "Sap" above the sawmill, and the game will crash.

**Comment by cl3w** [comment]
Crashlog:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-72-core.jar)
  SFRCore (SolarFluxReborn_1.12.1-3.40r.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  HammerCoreCore (HammerCore-1.12.1-1.9.4.7.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/29/17 5:27 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at cofh.thermalexpansion.util.Utils.isAccessibleOutput(Utils.java:23)
	at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:84)
	at cofh.thermalexpansion.block.machine.TileSawmill.transferOutput(TileSawmill.java:259)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_73660_a(TileMachineBase.java:134)
	at cofh.thermalexpansion.block.machine.TileSawmill.func_73660_a(TileSawmill.java:117)
	at net.minecraft.world.World.func_72939_s(World.java:1811)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cofh.thermalexpansion.util.Utils.isAccessibleOutput(Utils.java:23)
	at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:84)
	at cofh.thermalexpansion.block.machine.TileSawmill.transferOutput(TileSawmill.java:259)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_73660_a(TileMachineBase.java:134)
	at cofh.thermalexpansion.block.machine.TileSawmill.func_73660_a(TileSawmill.java:117)

-- Block entity being ticked --
Details:
	Name: thermalexpansion:machine_sawmill // cofh.thermalexpansion.block.machine.TileSawmill
	Block type: ID #845 (tile.cofh.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-227,13,228), Chunk: (at 13,0,4 in -15,14; contains blocks -240,0,224 to -225,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #845 (tile.cofh.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1811)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 634 Drop: 0
	Level seed: -2823551635573663957
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-168,64,240), Chunk: (at 8,4,0 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5082744 game time, 5091057 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 104238 (now: false), thunder time: 89981 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2143472312 bytes (2044 MB) / 4133486592 bytes (3942 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms512m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.41 Powered by Forge 14.22.1.2485 93 mods loaded, 92 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version               | Source                                          | Signature                                |
	|:--------- |:------------------------ |:--------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.1                | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                      | 9.19                  | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99             | forge-1.12.1-14.22.1.2485.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.22.1.2485          | forge-1.12.1-14.22.1.2485.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | actuallyadditions        | 1.12.1-r121           | ActuallyAdditions-1.12.1-r121.jar               | None                                     |
	| UCHIJAAAA | morphtool                | 1.2-16                | Morph-o-Tool-1.2-16.jar                         | None                                     |
	| UCHIJAAAA | autoreglib               | 1.3-14                | AutoRegLib-1.3-14.jar                           | None                                     |
	| UCHIJAAAA | crafttweaker             | 4.0.8                 | CraftTweaker2-1.12-4.0.8.jar                    | None                                     |
	| UCHIJAAAA | mtlib                    | @VERSION@             | MTLib-3.0.1.jar                                 | None                                     |
	| UCHIJAAAA | modtweaker               | 4.0.4                 | modtweaker-4.0.4.jar                            | None                                     |
	| UCHIJAAAA | jei                      | 4.7.11.102            | jei_1.12.2-4.7.11.102.jar                       | None                                     |
	| UCHIJAAAA | base                     | 3.4.2                 | base-1.12-3.4.2.jar                             | None                                     |
	| UCHIJAAAA | betterbedrockgen         | 6.0.2                 | BetterBedrockGenerator-1.12-6.1.1.jar           | None                                     |
	| UCHIJAAAA | betterbuilderswands      | 0.11.1                | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | hammercore               | 1.9.4.7               | HammerCore-1.12.1-1.9.4.7.jar                   | None                                     |
	| UCHIJAAAA | blackholestorage         | 18r                   | BlackHoleStorage-1.12.1-18r.jar                 | None                                     |
	| UCHIJAAAA | bookshelf                | 2.1.441               | Bookshelf-1.12.1-2.1.441.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | codechickenlib           | 3.1.3.313             | CodeChickenLib-1.12-3.1.3.313-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux             | 2.0.1                 | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore             | 2.3.3                 | BrandonsCore-1.12-2.3.3.132-universal.jar       | None                                     |
	| UCHIJAAAA | sonarcore                | 5.0.2                 | sonarcore-1.12.2-5.0.2.jar                      | None                                     |
	| UCHIJAAAA | calculator               | 5.0.1                 | calculator-1.12.2-5.0.1.jar                     | None                                     |
	| UCHIJAAAA | chameleon                | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | chickenchunks            | 2.4.0.70              | ChickenChunks-1.12-2.4.0.70-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ctm                      | MC1.12-0.2.3.9        | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCHIJAAAA | chisel                   | MC1.12-0.0.14.18      | Chisel-MC1.12-0.0.14.18.jar                     | None                                     |
	| UCHIJAAAA | chiselsandbits           | 14.9                  | chiselsandbits-14.9.jar                         | None                                     |
	| UCHIJAAAA | cofhcore                 | 4.3.6                 | CoFHCore-1.12-4.3.6.14-universal.jar            | None                                     |
	| UCHIJAAAA | cofhworld                | 1.0.1                 | CoFHWorld-1.12-1.0.1.8-universal.jar            | None                                     |
	| UCHIJAAAA | cyclopscore              | 0.10.21               | CyclopsCore-1.12-0.10.21.jar                    | None                                     |
	| UCHIJAAAA | commoncapabilities       | 1.4.0                 | CommonCapabilities-1.12-1.4.0.jar               | None                                     |
	| UCHIJAAAA | ctgui                    | 1.0.0                 | CraftTweaker2-1.12-4.0.8.jar                    | None                                     |
	| UCHIJAAAA | crafttweakerjei          | 2.0.0                 | CraftTweaker2-1.12-4.0.8.jar                    | None                                     |
	| UCHIJAAAA | cucumber                 | 1.0.2                 | cucumber[1.12]-1.0.2.jar                        | None                                     |
	| UCHIJAAAA | waila                    | 1.8.20                | Hwyla-1.8.20-B35_1.12.jar                       | None                                     |
	| UCHIJAAAA | darkutils                | 1.7.171               | DarkUtils-1.12.1-1.7.171.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | forestry                 | 5.5.6.198             | forestry_1.12.2-5.5.6.198.jar                   | None                                     |
	| UCHIJAAAA | eleccore                 | 1.8.430               | ElecCore-1.12-1.8.430.jar                       | None                                     |
	| UCHIJAAAA | deepresonance            | 1.4.9                 | deepresonance-1.12-1.4.9.jar                    | None                                     |
	| UCHIJAAAA | draconicevolution        | 2.3.4                 | Draconic-Evolution-1.12-2.3.4.265-universal.jar | None                                     |
	| UCHIJAAAA | enderstorage             | 2.4.0.122             | EnderStorage-1.12-2.4.0.122-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | energyconverters         | 1.0.1.2               | energyconverters_1.12.1-1.0.1.2.jar             | None                                     |
	| UCHIJAAAA | energysynergy            | 1.1.3                 | EnergySynergy-1.12-1.1.3.jar                    | None                                     |
	| UCHIJAAAA | valkyrielib              | 1.12-2.0.4b           | valkyrielib-1.12.X-2.0.4b.jar                   | None                                     |
	| UCHIJAAAA | environmentaltech        | 1.12.X-2.0.4a         | environmentaltech-1.12.X-2.0.4a.jar             | None                                     |
	| UCHIJAAAA | extendedcrafting         | 1.0.4                 | extendedcrafting-1.12-1.0.4.jar                 | None                                     |
	| UCHIJAAAA | fastleafdecay            | v14                   | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJAAAA | fluxnetworks             | 3.0.1                 | fluxnetworks-1.12.2-3.0.1.jar                   | None                                     |
	| UCHIJAAAA | ichunutil                | 7.0.2                 | iChunUtil-1.12.2-7.0.2.jar                      | None                                     |
	| UCHIJAAAA | mcmultipart              | 2.3.3                 | MCMultiPart-2.3.3.jar                           | None                                     |
	| UCHIJAAAA | ftbl                     | 4.2.2                 | FTBLib-4.2.2.jar                                | None                                     |
	| UCHIJAAAA | ftbu                     | 4.2.1                 | FTBUtilities-4.2.1.jar                          | None                                     |
	| UCHIJAAAA | immersiveengineering     | 0.12-74               | ImmersiveEngineering-0.12-74.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | integrateddynamics       | 0.9.3                 | IntegratedDynamics-1.12-0.9.3.jar               | None                                     |
	| UCHIJAAAA | integrateddynamicscompat | 1.0.0                 | IntegratedDynamics-1.12-0.9.3.jar               | None                                     |
	| UCHIJAAAA | integratedtunnels        | 1.3.3                 | IntegratedTunnels-1.12-1.3.3.jar                | None                                     |
	| UCHIJAAAA | inventorytweaks          | 1.63+beta.108.6ff67c4 | InventoryTweaks-1.63+beta.108.jar               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest                | 1.12-7.0.31.818       | ironchest-1.12-7.0.31.818.jar                   | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.1-5.5.2b1        | journeymap-1.12.1-5.5.2b1.jar                   | None                                     |
	| UCHIJAAAA | jeresources              | 0.8.4.25              | JustEnoughResources-1.12.1-0.8.4.25.jar         | None                                     |
	| UCHIJAAAA | longfallboots            | 1.2.1a                | longfallboots-1.2.1a.jar                        | None                                     |
	| UCHIJAAAA | mousetweaks              | 2.8                   | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCHIJAAAA | mysticalagriculture      | 1.6.5                 | mysticalagriculture-1.12-1.6.5.jar              | None                                     |
	| UCHIJAAAA | mysticalagradditions     | 1.2.5                 | mysticalagradditions-1.12-1.2.5.jar             | None                                     |
	| UCHIJAAAA | notenoughwands           | 1.5.9                 | notenoughwands-1.12-1.5.9.jar                   | None                                     |
	| UCHIJAAAA | openglider               | @VERSION@             | OpenGlider-1.12.1-1.1.0.jar                     | None                                     |
	| UCHIJAAAA | overloaded               | 0.0.44                | Overloaded-1.12.1-0.0.44.jar                    | None                                     |
	| UCHIJAAAA | portalgun                | 7.0.0                 | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UCHIJAAAA | reborncore               | 3.4.8.138             | RebornCore-1.12.2-3.4.8.138-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | quantumstorage           | 4.4.3                 | QuantumStorage-1.12-4.4.3.jar                   | None                                     |
	| UCHIJAAAA | randomthings             | 4.0.8                 | RandomThings-MC1.12.2-4.0.8.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | rangedpumps              | 0.5                   | rangedpumps-0.5.jar                             | None                                     |
	| UCHIJAAAA | realfilingcabinet        | 0.1.21                | realfilingcabinet-1.12.1-0.1.21.jar             | None                                     |
	| UCHIJAAAA | thermalfoundation        | 2.3.6                 | ThermalFoundation-1.12-2.3.6.16-universal.jar   | None                                     |
	| UCHIJAAAA | thermalexpansion         | 5.3.6                 | ThermalExpansion-1.12-5.3.6.20-universal.jar    | None                                     |
	| UCHIJAAAA | redstonearsenal          | 2.3.6                 | RedstoneArsenal-1.12-2.3.6.16-universal.jar     | None                                     |
	| UCHIJAAAA | storagedrawers           | 1.12-5.2.5            | StorageDrawers-1.12.1-5.3.3.jar                 | None                                     |
	| UCHIJAAAA | refinedstorage           | 1.5.21                | refinedstorage-1.5.21.jar                       | None                                     |
	| UCHIJAAAA | xreliquary               | 1.12-1.3.4.710        | Reliquary-1.12-1.3.4.710.jar                    | None                                     |
	| UCHIJAAAA | rflux                    | 0.1.2                 | rflux-1.12-0.1.2.jar                            | None                                     |
	| UCHIJAAAA | rftools                  | 7.12                  | rftools-1.12-7.12.jar                           | None                                     |
	| UCHIJAAAA | rftoolscontrol           | 1.6.8                 | rftoolsctrl-1.12-1.6.8.jar                      | None                                     |
	| UCHIJAAAA | rftoolsdim               | 5.05                  | rftoolsdim-1.12-5.05.jar                        | None                                     |
	| UCHIJAAAA | simplequarry             | 1.0.8                 | SimpleQuarry-1.12.1-1.0.8.jar                   | None                                     |
	| UCHIJAAAA | solarfluxreborn          | 3.40r                 | SolarFluxReborn_1.12.1-3.40r.jar                | None                                     |
	| UCHIJAAAA | thermaldynamics          | 2.3.6                 | ThermalDynamics-1.12-2.3.6.13-universal.jar     | None                                     |
	| UCHIJAAAA | tp                       | 1.12                  | tinyprogressions-1.12-3.2.10 - Beta.jar         | None                                     |
	| UCHIJAAAA | torchmaster              | 1.6.1.53              | torchmaster_1.12.2-1.6.1.53.jar                 | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHIJAAAA | usefulnullifiers         | 1.4.1                 | usefulnullifiers-1.4.1.jar                      | None                                     |
	| UCHIJAAAA | wailaharvestability      | 1.1.12                | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UCHIJAAAA | wawla                    | 2.5.243               | Wawla-1.12.1-2.5.243.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | xnet                     | 1.4.1                 | xnet-1.12-1.4.1.jar                             | None                                     |
	| UD        | solarfluxreborncore      | 3.40r                 | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-72-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
SFRCore (SolarFluxReborn_1.12.1-3.40r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
HammerCoreCore (HammerCore-1.12.1-1.9.4.7.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.4.8.138
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by cl3w** [comment]
i tryd to reproduce the error on a new profile on 1.12.2 with newest forge version and just thermal expansion, quantumtank & jei installed, here the log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Oops.

Time: 10/29/17 5:55 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at cofh.thermalexpansion.util.Utils.isAccessibleOutput(Utils.java:23)
	at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:84)
	at cofh.thermalexpansion.block.machine.TileSawmill.transferOutput(TileSawmill.java:259)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_73660_a(TileMachineBase.java:134)
	at cofh.thermalexpansion.block.machine.TileSawmill.func_73660_a(TileSawmill.java:117)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cofh.thermalexpansion.util.Utils.isAccessibleOutput(Utils.java:23)
	at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:84)
	at cofh.thermalexpansion.block.machine.TileSawmill.transferOutput(TileSawmill.java:259)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_73660_a(TileMachineBase.java:134)
	at cofh.thermalexpansion.block.machine.TileSawmill.func_73660_a(TileSawmill.java:117)

-- Block entity being ticked --
Details:
	Name: thermalexpansion:machine_sawmill // cofh.thermalexpansion.block.machine.TileSawmill
	Block type: ID #280 (tile.cofh.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-748,1,-42), Chunk: (at 4,0,6 in -47,-3; contains blocks -752,0,-48 to -737,255,-33), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #280 (tile.cofh.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['cl3w'/0, l='New World', x=-747.71, y=1.00, z=-44.55]]
	Chunk stats: ServerChunkCache: 290 Drop: 0
	Level seed: 3118996211127937988
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock;1;village
	Level spawn location: World: (-751,4,-46), Chunk: (at 1,0,2 in -47,-3; contains blocks -752,0,-48 to -737,255,-33), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 3525 game time, 3525 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 124674 (now: false), thunder time: 92137 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1208407016 bytes (1152 MB) / 2037383168 bytes (1943 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2517 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                                        | Signature                                |
	|:--------- |:----------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.0.2517.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.0.2517 | forge-1.12.2-14.23.0.2517.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | codechickenlib    | 3.1.3.313    | CodeChickenLib-1.12-3.1.3.313-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux      | 2.0.1        | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore          | 4.3.6        | CoFHCore-1.12-4.3.6.14-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld         | 1.0.1        | CoFHWorld-1.12-1.0.1.8-universal.jar          | None                                     |
	| UCHIJAAAA | jei               | 4.8.0.105    | jei_1.12.2-4.8.0.105.jar                      | None                                     |
	| UCHIJAAAA | reborncore        | 3.4.8.138    | RebornCore-1.12.2-3.4.8.138-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | quantumstorage    | 4.4.3        | QuantumStorage-1.12-4.4.3.jar                 | None                                     |
	| UCHIJAAAA | thermalfoundation | 2.3.6        | ThermalFoundation-1.12-2.3.6.16-universal.jar | None                                     |
	| UCHIJAAAA | thermalexpansion  | 5.3.6        | ThermalExpansion-1.12-5.3.6.20-universal.jar  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.4.8.138
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['cl3w'/0, l='New World', x=-747.71, y=1.00, z=-44.55]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by gigabit101** [comment]
fixed in 4.4.4

**Comment by cl3w** [comment]
your bugfix works as intended.
could load my world again.

Testet on 1.12.1 game profile and my 1.12.2 test profile. both versions working
