### ISSUE TITLE
Qsu upgrades

### ISSUE THREAD

**Issue by gigabit101** [gigabit101/QuantumStorage#12]
In world upgrades

**Comment by Protheus** [comment]
Mekanism has a nice upgrade system. You use upgrades on existing machines that you don't have to break.

**Comment by gigabit101** [comment]
im already doing it and have it working lol

**Comment by Protheus** [comment]
please don't tease :-)

**Comment by gigabit101** [comment]
they work just need textures and I am bad at them....

**Comment by Protheus** [comment]
I will have a goo at some textures and send them to you

**Comment by gigabit101** [comment]
Textures are always welcome

**Comment by Protheus** [comment]
Was in the progress of redoing the textures to a soartex feel and 64, will make some 16 versions

**Comment by gigabit101** [comment]
Awesomeness

**Comment by Protheus** [comment]
http://imgur.com/rUL7cw8 - first try at the the storage unit (64)

**Comment by gigabit101** [comment]
Well they work perfect just need textures then new Beta release ;)
