### ISSUE TITLE
Quantum battery tooltip update issues

### ISSUE THREAD

**Issue by brisingraerowing** [gigabit101/QuantumStorage#120]
I placed a Quantum Battery into a Mekanism Creative Power Cube to charge it, and I have to exit / reenter the Gui to see the battery's progress, as the tooltip doesn't update as the item charges. That is a bit annoying. The same goes for the player inventory as well; it has to be closed and reopened to see the charge change.

**Comment by gigabit101** [comment]
yeah this is a issue I have noticed will be fixed asap

**Comment by gigabit101** [comment]
Fixed in latest build

**Comment by brisingraerowing** [comment]
Now the tooltip for the first battery that gets charged shows on all batteries, even in the creative inventory.
