### ISSUE TITLE
QSU duplication bug

### ISSUE THREAD

**Issue by Mrminesheeps** [gigabit101/QuantumStorage#123]
So, I was setting up some botania automation, and I used the Extra Utilities 2 Mechanical User to place blocks. I just finished, and was placing down some QSU's to store the output. But when I placed one, it got turned around, and when I broke it, it dropped two QSU's. I placed it multiple times to see if it was a one-off bug, but it did it every time. I placed the QSU elsewhere, and it placed and broke just like anything else would. This occured on the 1.10 version of your mod, on singleplayer.

**Comment by gigabit101** [comment]
This is fixed in 1.12+

**Comment by Mrminesheeps** [comment]
I guess I marked it wrong, it's mod version 3.3.6 for minecraft 1.10.2.

**Comment by Mrminesheeps** [comment]
Are you saying that the bug is unfixable or otherwise for this version of MC?

**Comment by gigabit101** [comment]
1.10 is no longer supported so this will not be fixed
