### ISSUE TITLE
Quantum Fluid Disk holds more than one type of fluid.

### ISSUE THREAD

**Issue by Chunkey** [gigabit101/QuantumStorage#126]
On QuantumStorage-1.12-4.4.6 and  Refined storage 1.5.30.
Quantum fluid disk holds many types of fluids. Not sure if this is intended but it's pretty OP. Especially with the inclusion of rebornstorage adding larger fluid cells. I know I can disable the disk but I'd like to have quantum tank style disks in my system.
Thx^^

**Comment by gigabit101** [comment]
Yup that was how its meant to work,
It works the same way as refined storage disks.

You can always filter it in a drive bay or use a external Interface on a QuantumTank ;)
