### ISSUE TITLE
[Suggestion] Quantum Disc Recipes with RebornStorage

### ISSUE THREAD

**Issue by Mohron** [gigabit101/QuantumStorage#128]
Would you be willing to add Integration with RebornStorage so Quantum Discs would require the largest Reborn Storage disc instead of Refined Storage's largest disc?  When both mods are in a pack, Reborn Storage's discs become pointless otherwise.

![image](https://user-images.githubusercontent.com/3623122/34642902-9f856f04-f2e0-11e7-8e68-20ad34b2d08b.png)

![image](https://user-images.githubusercontent.com/3623122/34642898-94c160c8-f2e0-11e7-90f5-caa29ed5928b.png)

**Comment by gigabit101** [comment]
Yeah its on my TODO

**Comment by Mohron** [comment]
Perfect, I look forward to it!
