### ISSUE TITLE
[1.12-4.4.6] Quantum Storage Crafter Duplication Bug

### ISSUE THREAD

**Issue by mrmorder** [gigabit101/QuantumStorage#129]
This is a weird one as I can only get it to reproduce when placing the QSC on Astral Sorcery [1.12.2-1.8.4] marble and only when facing north.

https://i.imgur.com/Rrf4ext.gifv

Place the QSC down and then right click immediately after and a new one appears in inventory.

Playing Unbound beta. https://minecraft.curseforge.com/projects/unbound-modpack/files/2520704#additional-files

**Comment by gigabit101** [comment]
Can not reproduce this issue
