### ISSUE TITLE
Enhancement Request - Fluid Storage

### ISSUE THREAD

**Issue by Thiana** [gigabit101/QuantumStorage#13]
Since you're adding new QSU variants could you please consider adding a version of the QSU for mass fluid storage? QST perhaps? Thank you.

**Comment by Protheus** [comment]
:+1

**Comment by gigabit101** [comment]
Sure why not easy to do

**Comment by gigabit101** [comment]
@Thiana @Protheus look good to u ?? http://puu.sh/llh8O/6372ca4d94.jpg

**Comment by Thiana** [comment]
If you can add the name of the liquid being stored it's good :) For colorblind people some of the liquids can be a little difficult to differentiate. Thanks.

**Comment by gigabit101** [comment]
sure

**Comment by gigabit101** [comment]
U can pick them up and they keep there fluid fyi

**Comment by gigabit101** [comment]
better ?? http://puu.sh/llkVq/e28ec88270.png

**Comment by Thiana** [comment]
Perfect :) Thank you.

**Comment by gigabit101** [comment]
I will release a new version as soon as I get some textures for the upgrade
items
