### ISSUE TITLE
[Suggestion] Ability to upgrade crates and keep contents

### ISSUE THREAD

**Issue by psychofad** [gigabit101/QuantumStorage#133]
Would be nice to have some way of upgrading the storage crates while retaining the contents.  This could be either an in-place upgrade similar to the way the iron chests mod does it, or simply break and craft upgrade as normal but copy the NBT data of the crate used in the craft over to the upgraded crate so nothing is lost.

**Comment by Xetaxheb** [comment]
This would be very nice, pretty much every other mod that has upgradeable containers does this and it was a huge shock to lose all of what was in my chest.

**Comment by gigabit101** [comment]
This is something I will need to look into, Not something I have done before so will require some testing :D
