### ISSUE TITLE
QSU causes chunk errors/timeouts

### ISSUE THREAD

**Issue by mrsnowfoxy** [gigabit101/QuantumStorage#136]
We are having an issue on our skyfactory 3 server where the QSU will eventually cause anyone that goes near it to time out and the server to lock up.

Details:
On our server someone set up a few  QSUs to store mass amounts of essences and seeds from mystical agriculture,  he was using some Janky system of Immersive Engineering  conveyors  to transfer into the QSU (its dumb I know) and my guess is either the IE conveyor belts were overloaded and spewing items everywhere, or the QSU was dumping its items  and causing a chunk its in to error and lock up the server and time out any players in that chunk. I was wondering if there is a fix for this aside from obviously ditching IE?

**Comment by gigabit101** [comment]
The QSU has no way of dumping its items so there is nothing I can do about this sorry to say, best bet is to run xu_killall to remove the items from the ground.
