### ISSUE TITLE
GUI Does Not Close When Block Is Broken

### ISSUE THREAD

**Issue by Darkosto** [gigabit101/QuantumStorage#137]
When looking at any of the Quantum Storage GUI's and the block is broken (other player, TNT, etc.) the GUI does not close and retains its inventory. This can lead to a number of issues such as duplication glitches with other mods.

Would you please consider force closing the GUI's when the blocks are broken.

Thank you!
Darkosto

**Comment by modmuss50** [comment]
The proper fix for this lies within reborn core, but you overriding canInteractWith in 2 classes so having a fix in would still not fix it.

I also need to see if I can find a reliable way to get the tile that the player is using. So watch out for an optional method to set the tile in the RebornContainer.

**Comment by modmuss50** [comment]
Ok, ive open a pull request (even tho I committed it to this repo by accident XD). Let me know when you plan to release it and ill push an RC update at the same time.

**Comment by gigabit101** [comment]
@modmuss50 Uploading to curse now
