### ISSUE TITLE
[v1.12.2 - 4.4.10] Crates Crash

### ISSUE THREAD

**Issue by Yhuxz** [gigabit101/QuantumStorage#139]
Tried to use the diamond crate, and it crash, tested on iron and gold same result. (with and without optifine)

Forge: 2611
Optifine: C9
QS: 4.4.10

**Comment by gigabit101** [comment]
I need the log

**Comment by Yhuxz** [comment]
[crash-2018-03-27_02.18.32-client.txt](https://github.com/gigabit101/QuantumStorage/files/1849365/crash-2018-03-27_02.18.32-client.txt)

**Comment by gigabit101** [comment]
Update RebornCore

**Comment by Yhuxz** [comment]
Well curseforge didn't notify me 5 hours ago; will test if works

(edit)
since december
