### ISSUE TITLE
[Minor Issue] Crates Texture Overlap

### ISSUE THREAD

**Issue by Yhuxz** [gigabit101/QuantumStorage#140]
Just noticed that the crates has 17h x 16w size and can overlap if you place a block above it

![2018-03-27_05 06 32](https://user-images.githubusercontent.com/36140746/37933077-c14df7de-317c-11e8-822c-b165d8c4cac8.png)

**Comment by Yhuxz** [comment]
I see what you did there, its nice to see the crates can blend in their wood variants and each other while stacked but if using as is ,render issue happens

**Comment by Nexans20** [comment]
Fixed in dev

**Comment by gigabit101** [comment]
new build on curse

**Comment by Yhuxz** [comment]
Thanks for the heads up
