### ISSUE TITLE
1.12.2(quantum battery not charging) in Rf tools power cell or mekanism

### ISSUE THREAD

**Issue by SDUBZ** [gigabit101/QuantumStorage#141]
The other day i crafted a battery from quantum storage and then tried charging it in a rf tools power cell it would take the power and didnt charge then i tried putting it in mekanism charge slots with no luck also
Rf toosl: rftools-1.12-7.31
Quantum storage: QuantumStorage-1.12-4.4.10
Mekanism/gen/tools: Mekanism-1.12.2-9.4.3.330

**Comment by gigabit101** [comment]
Just as a fyi it does not use the RF api, it uses the forge energy system that most mods support, there is still some other issues I need to resolve with the battery.

**Comment by 4rz0** [comment]
It does work for me, it's just that the tooltips don't update.

**Comment by gigabit101** [comment]
Fixed in 4.5.0
