### ISSUE TITLE
Crates & QSU's Duping and Deleting items + too many items in one crate

### ISSUE THREAD

**Issue by MineCrak** [gigabit101/QuantumStorage#144]
(Client: Win7sp1+)
Java 8
Minecraft 1.12.2
Forge 2611
RebornCore  1.12.2-3.6.13.225-universal (And earlier versions)
QuantumStorage-1.12-4.4.10 (And earlier versions)
'Blockpack-13' from 'Mental Block' Server (linked and listed below)
* Survival mode

Hello, this report is based on my and others experiences with this mod while using it on a Minecraft server called Mental Block: https://discord.gg/JSNyve4 . These problems have been experienced with the **Diamond Crates**, I assume it affects all crates but we only ever really use diamond crates. 

**Deletion of items:** At seemingly random times the items I will place into a crate will not be in it again the next time I open it, even just minutes later with the chests being in my sight the entire time. The items that go missing are always only ones that I've just placed into the crate and in the amounts that they were placed, it's never items that were already there when I place the crate down. - This happens so often that I now break the crates after every single time I place something into them, pick them up then place them on the ground again. This has so far kept items from disappearing but is extremely annoying and can be forgotten from time to time resulting in losses. I have lost many stacks of wood that I spent a long time chopping, enchanted Elytra's etc. 

**Duping:** At seemingly random (though perhaps not completely) times items and stacks that I will take out of crates will end up being back in the crates I took them out of, in addition to the originals that I took out, duping. Sometimes all of the things I took out last time will be back again, and sometimes only some of them. For each slot an item was taken out of the duped item/s are back in the same slot and back to the exact same number that they were before I removed any. Sometimes only some of the slots are duped and others not. 

- One reasonably reliable way I have found to **purposely reproduce the duping effect** is to take items/stacks/crates out of a placed crate then go through a nether portal. I then return and check the chest. The duping does not happen with every trip but if you keep doing it it will happen often enough to be usable for large scale duping. I demonstrated this to the server owner, Wozat, by duping a ridiculous number of full crates this way in a short period of time. 

My above mentioned demonstration ended up **poisoning the part of the map** I was at up to full loading range when I placed all of the duped crates into one crate then broke it. As soon as I broke it I received the following error and lost connection with the server. It was found that anyone getting within load range of the anomaly would have the same thing happen to them and be unable to ever get back on the server. The admin was finally able to /kill the floating crate item and return the server to normal, minus all of my original stuff which happened to also be in the crate. 

"Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097155bytes where max allowed: 2097152"

![blackhole error](https://user-images.githubusercontent.com/1588565/38623838-7fe1e1a8-3d5b-11e8-8cf6-201561c1b467.png)

You can feel free to download the modpack for this server from the discord #info channel, it is currently "Blockpack-13.zip", and test this issue on the server if you wish as it is public. I will also list the mods used below. The bottom section of mods are in the optional mods folder in the pack, I am using them all; however another player who says that he does not use the optional mods also reported the duping bug occurring to him:  

**Blockpack-13** / 'Mental Block' Discord: https://discord.gg/JSNyve4

RebornCore  1.12.2-3.6.13.225-universal
CodeChickenLib  1.12.2-3.1.6.339-universal
CTM  MC1.12-0.2.3.12
Movingworld  1.12-6.342-full

ArchitectureCraft  1.12-2.68
Buildcraft  7.99.15
Chisel  1.12.2-0.2.0.31
Cubic Chunks  1.12.2-0.0.824.0-SNAPSHOT-all
DaVinci's Vessels  1.12-6.340-full
Ender Storage  1.12.2-2.4.2.126-universal
Faster Ladder Climbing  1.12-0.1-127
Hardcore Ore  1.12.2-0.1.9b
OpenBlocks Elevator Mod  1.12.2-1.3.6
Quantum Storage  1.12-4.4.10
Utility Worlds  1.12_1.1.0
Vanilla Death Chest  1.12.2-1.1.1.0

**(Server-side only)**

FastLeafDecay v14
Morpheus  1.12-3.3.2

**(Optional Client mods)** 

BetterFPS  1.4.8
FoamFix  1.12.2-0.9.4-Anarchy
Here's What You're Looking At  'Hwyla'  1.8.23-B38_1.12
Just Enough Items  1.12.2-4.8.5.147
Just Enough Pattern Banners  'jepb'  1.12-1.2.1
Just Enough Resources  1.12.2-0.8.5.27
More Overlays (CC version)  1.13-cc
TrueType Font Replacement aka BetterFonts  'TTFR'  1.12.1-1.9.1
Unride Keybind  1.0b
What Are We Looking At  'Wawla'  1.12.2-2.5.253
Xaero's Minimap  1.14.9_Forge_1.12

**Comment by MineCrak** [comment]
Troubleshooting update. 

This might be a location(coordinate) based problem. I've tried doing the portal trick through someone elses portal from a completely different part of the world and have not yet been able to replicate this. I then went back to my portal room and it worked the first time through. Here are the relevant coordinates:

Overworld portal location: -653, 82, 946
Netherside portal location: -82, 82, 120

Both of my portals are facing North-South. 

The portal I tried that did not do this was facing East-West. 

* A reminder that this is not just a portal issue. These effects happen without going through any portals, just more randomly. 

The overworld coordinates might be of importance though since all my experiences of this happening have been while my crates were in the same general overworld area x and z wise. It happened also at far higher y values in the same x,z. The exact coords change every time as I pack my crates into my personal inventory or enderchests whenever I log out then unpack them someplace convenient depending on where in or near my mesa I'm working. 
-653, 82, 946

---------------------------------
Wozat, server admin, has only experienced the duping in conjunction with BuildCraft pipes connected to crates sometimes duping items. 

Another person new to the server just reported today having the same duping + deletion problems that I have been having. Sounded like it happened in a specific area though. I will try to get coords of where it happened to him.

**Comment by MineCrak** [comment]
Even with the same modpack and install that I log into the Mental Block server with I cannot replicate this in an ssp vanilla world at the same coords. But the server world was made with the custom-cubic worldtype and seed "30" without quotes. I'll have to try that next despite not having the specific preset string for that world to go with it. 

* The problem is still easily replicated on server though anywhere on my base.

**Comment by MineCrak** [comment]
Now, on the same server I've finally noticed the deletion bug in a QSU. It wasn't even in one of the normal dimensions. 

I was in my Mining World Dimension, Utility Worlds mod. 
I had used up the last of my sandstone stacks so the QSU was empty. I left the dim and got more sandstone then returned and placed approx 6 stacks into the QSU. They showed in it and the block was rotating in it. I then left the dim for perhaps 10 min or less then returned and noticed the block was gone from the QSU. I opened it and found it empty..

Considering how QSU's are used this could have happened many times without me necessarily noticing before..

**Comment by gigabit101** [comment]
Can I get the server files as I am having issues replicating this issue.

**Comment by MineCrak** [comment]
Wozat, the person who runs that server sounds like he would be happy to work with you to solve this. He has read this page and is aware of the issue. Which server files do you need? 

If you like you can work with him and I directly on his Discord @ https://discord.gg/JSNyve4

**Comment by gigabit101** [comment]
Ok I am currently away so it will be a day or 2,I am going to need the map, mods, config so it might be better just to zip up the whole Minecraft server and send it to me

**Comment by BaccarWozat** [comment]
OK, here [link removed after 7 months] is the entire server map including the modlist and configs, from last week's backup.
