### ISSUE TITLE
Quantum batteries

### ISSUE THREAD

**Issue by Lervfo** [gigabit101/QuantumStorage#145]
Issues

1. All batteries share the same value.
2. Batteries are fully charged when crafted.
3. Batteries suddenly drop it's charge randomly.
4. Batteries won't charge, or it's a GUI bug where the values won't update.

Non-issue related.
Can we get more information about the mod? How every item works. Like batteries, do they share their storage? Crafting recipes, tips, and tricks etc..

I've got an idea. 

Keep the batteries as individual storage units that can be used as normal batteries.
Add another item called "Quantum Power transmitter" or something that acts like a battery, but shares the charge with other batteries sharing the same channel. So that people could have one in their inventory and another one in a power cell to keep it charged.

Could we have a wireless charger, like in the EnderIO, but with a greater range?
OR, that there's this quantum power transmitter and you could carry the receiver in the inventory and charge items at an unlimited or MaxInt range?

I've got more ideas.

**-Lervfo**

**Comment by gigabit101** [comment]
Fixed in 4.5.0
