### ISSUE TITLE
QSU Crashing When Placed and Right Clicked

### ISSUE THREAD

**Issue by marikc0** [gigabit101/QuantumStorage#146]
MC 1.12.2 is crashing when placing the QSU and then right clicking on it. This is with QuantumStorage-1.12-4.5.0.jar.

**Comment by gigabit101** [comment]
Log or it didn't happen.

**Comment by benderisgo** [comment]
I have the same issue. Using Direwolf20 1.12.2. 

Can reproduce by placing qsu then right clicking for gui.

Here is my crash report. 

https://pastebin.com/cMDyRh8W

**Comment by gigabit101** [comment]
Update RebornCore

**Comment by gigabit101** [comment]
Also @benderisgo  QS is not in Direwolf20 1.12.2. did you add it yourself? If so RebornCore will need updating

**Comment by benderisgo** [comment]
Yes I did actually add some stuff including QS. Will update core and report results.

**Comment by benderisgo** [comment]
Also thanks for the quick reply :)

**Comment by benderisgo** [comment]
Ok I updated reborn storage, and reborn core, in addition I had to update refined storage and refined storage additions. (api or something). 

Everything seems to work as expected.  Thanks again for the quick reply.
