### ISSUE TITLE
Quantum Bag Blacklist config

### ISSUE THREAD

**Issue by justinrusso** [gigabit101/QuantumStorage#147]
Hello,

I would love if there was a way to blacklist items from the backpack. Specifically, my goal is to blacklist other bags and the quantum bag from being able to be put into the Quantum Bag.

This would be for MC 1.12.2. I've also requested this support for other mods such as the betweenlands if you'd like some reference for how to implement it https://github.com/Angry-Pixel/The-Betweenlands/issues/601

Referencing: https://github.com/DarkPacks/SevTech-Ages/issues/2654

**Comment by gigabit101** [comment]
This can be easily added, I will get to it at some point.
