### ISSUE TITLE
Explosions Delete ALL Items from Crates

### ISSUE THREAD

**Issue by desagas** [gigabit101/QuantumStorage#148]
Playing in 1.12-4.5.0, in ATM3 - May 28th, in 1.12.2.

Creeper approached as I was unloading a diamond crate from an expedition, and when the creeper exploded, so did the crate, deleting the crate. I understand this mechanic, as this is the resistance set in your mod. However, the coding in the mod does not allow the crate itself to drop its inventory when it is destroyed. I rage quit.

To reproduce: place diamond crate, place tnt or creeper by crate, make it explode.

Also, when destroyed in creative mode, I would expect it to drop its items, like vanilla chests, or crates from Actually Additions. Needless to say, losing the amount of items that can fit in a diamond crate can be a huge setback, and a huge deterrent from ever using the crate again.

**Comment by gigabit101** [comment]
fixed in dev
