### ISSUE TITLE
(Wierd) Quantum Storage Units Hogging Bandwidth

### ISSUE THREAD

**Issue by CreeperFace00** [gigabit101/QuantumStorage#149]
So, I've got kind of a weird one for you, apparently quantum storage units use A LOT of internet bandwidth, but they really only do it when placed close to each other.  

I first noticed the problem on my server when me and a lot of other players were having trouble logging into the server around my base (People with bad connections timed out instantly). Sitting idle at my base was using a constant 2.5-3 megabits/s which doesn't sound like much, but it causes problems when logging in. I ran a packet profiler and it showed SPacketUpdateTileEntity as the element using the most bandwidth.  (Sent 70334 packets and 23.4MB in the span of 1 minute)  

**Here is a picture of the setup**

![2018-07-10_00 41 34](https://user-images.githubusercontent.com/16279973/42496636-92709f5a-83db-11e8-962e-9480c7bcb4f5.png)
The problem happens with and without the storage buses.  

This isn't too big of a problem as I can just put them in another dimension, just thought I'd report it because it took me hours to figure out why players kept timing out

**Comment by gigabit101** [comment]
fixed in dev
