### ISSUE TITLE
1.8.9- Crash on Startup

### ISSUE THREAD

**Issue by WenXin20** [gigabit101/QuantumStorage#15]
Crash Log:
(https://github.com/gigabit101/QuantumStorage/files/121011/crash-2016-02-07_17.29.56-client.txt)

**Comment by gigabit101** [comment]
try this version https://www.dropbox.com/s/wqqtgax63xlv9z9/QuantumStorage-2.0.1.jar?dl=0

**Comment by WenXin20** [comment]
Ok

**Comment by WenXin20** [comment]
It still crashes the same way.

**Comment by gigabit101** [comment]
you are using RebornCore correct

**Comment by WenXin20** [comment]
No, did not realize it needed it, thanks.

**Comment by gigabit101** [comment]
It is listed on the Curse page but its my bad as well I forgot to re-add the the dep check

**Comment by gigabit101** [comment]
fixed in 2.0.2

**Comment by WenXin20** [comment]
Cool, thanks
