### ISSUE TITLE
QuantumStorage-1.12-4.6.0 Crash issue

### ISSUE THREAD

**Issue by CataclysmX** [gigabit101/QuantumStorage#151]
Hi,
the last version of QuantumStorage (QuantumStorage-1.12-4.6.0) crash with other mod
[lastest.log](https://github.com/gigabit101/QuantumStorage/files/2216329/2018-07-21-7.log)

but work with QuantumStorage 4.5.0.

**Comment by gigabit101** [comment]
4.6.0 requires Refined Storage 1.6+
