### ISSUE TITLE
[1.12.2] Crash while loading 4.6.0

### ISSUE THREAD

**Issue by joklbash** [gigabit101/QuantumStorage#152]
Forge: 14.23.4.2739
Quantum: 4.6.0
Refined Storage: 1.6

I'm getting a crash when loading after updating to RS 1.6 and QS 4.6. I created a new Minecraft instance with bare set of mods installed and fresh configs to test with and have the same issue. Only issue I've seen others post was when they didn't update RS for the new API, so I can't figure out what I'm missing.

Log:
https://pastebin.com/4kXyeRa5

**Comment by erindal** [comment]
I can confirm I have the same bug, same mod versions.

**Comment by Davoleo** [comment]
I'm having the same issue, it seems a common one
crash report: https://pastebin.com/W3a3LUVg

**Comment by gigabit101** [comment]
Fixed in dev
