### ISSUE TITLE
Quantum Storage unit not accepting more items

### ISSUE THREAD

**Issue by Nbome** [gigabit101/QuantumStorage#153]
Firstoff - I'm using QS 1.5.0 in my modpack. If this issue is fixed in 1.6.0 i'll look into updating this mod.

Problem: The QSU gets clogged - it does not transfer the items from the top slot to the storage itself. 
This problem can only be solved by taking all of the items out of the QSU and refill it freshly. The result is that I end up with a ME-system which randomly gets flooded with Iron/Gold/Stone etcetc and I have to check every of my 40 QSU to find out, which is clogged - extract millions of items and refill it again. This bug is completely random, the QSU may work for 330k items perfectly fine or get clogged after 300.

In this example it stopped after 2.3k - vanilla items, fed via storage bus of the ME-system (only exporting gold ofc). 
If I remove the top 64, they will just fill up again - removing gold from the bottom slot does not help either, except I empty it completely.
![qsu](https://user-images.githubusercontent.com/8324468/43386762-f10e4cf6-93e4-11e8-9bc4-bc29057c796e.jpg)

To reproduce - hook up a ME-system with a quarry and some QSU via storage bus.
This bug sadly is a complete dealbreaker...

**Comment by gigabit101** [comment]
Fixed in dev

**Comment by Nbome** [comment]
Great to hear, are you able to say by when this fix will be released?

**Comment by gigabit101** [comment]
Getting some other fixes rolled into this update so soon TM

**Comment by Nbome** [comment]
As of yesterdays 4.6.1, it is still an issue (if it was supposed to be fixed with this update)
Now all QSUs are clogged that are connected via Storage-bus. (Export-bus works as far as I could see)

**Comment by gigabit101** [comment]
Yes they will still be clogged but now that will not happen again, you will
need to empty them to unclog them

**Comment by Nbome** [comment]
The bug is still reproducable:
https://www.youtube.com/watch?v=QXKTJz4Ncwk

**Comment by gigabit101** [comment]
That link is not available..

**Comment by Nbome** [comment]
Sorry - my fault, did 'private' instead of 'not listed' - should be available now

**Comment by gigabit101** [comment]
Ok now that is odd, thanks for the video will review it more later when I
am not at work

**Comment by Nbome** [comment]
Some more fun for you
https://youtu.be/lw27Pe3nm8M

**Comment by gigabit101** [comment]
Oh I see what I did, revert to the last version to fix that issue
[facepalm]

**Comment by Nbome** [comment]
Some more interactions
https://www.youtube.com/edit?o=U&video_id=BbeNKXgdWuY

**Comment by Nbome** [comment]
Sorry - correct link is:
https://www.youtube.com/watch?v=BbeNKXgdWuY
