### ISSUE TITLE
Fluid disk creates an item disk

### ISSUE THREAD

**Issue by raoulvdberge** [gigabit101/QuantumStorage#154]
https://github.com/gigabit101/QuantumStorage/blob/db3ce137c73a7da28955eb9a73ec309a2d645c7b/src/main/java/QuantumStorage/compat/ItemQuantumStorageDiskFluid.java#L51

You're using `createDefaultItemDisk`, you want `createDefaultFluidDisk`.

Causes this: https://github.com/raoulvdberge/refinedstorage/issues/1934

Thank you.

**Comment by gigabit101** [comment]
Fixed in QuantumStorage-1.12-4.6.2
