### ISSUE TITLE
Quantum Storage / Fluid Disk uncraftable

### ISSUE THREAD

**Issue by RyanP1991** [gigabit101/QuantumStorage#155]
Using Quantum Storage version 4.6.1 and Refined Storage - 1.6.2 it seems that both the Quantum Storage Disk and Quantum Fluid Disk are both uncraftable and don't have a recipe in JEI. Currently using Forge - 14.23.4.2739

Sorry if this is a duplicate bug report.

**Comment by gigabit101** [comment]
Commented them out while testing and forgot to undo...

**Comment by RyanP1991** [comment]
Haha no worries.

**Comment by viveleroi** [comment]
I try my best to avoid being an "eta guy" but I would greatly appreciate if you could post an update with the fix for this. I was *just* about to start making all my quantum disks when I updated everything to RS 1.6, etc.

**Comment by gigabit101** [comment]
Fixed in QuantumStorage-1.12-4.6.2

**Comment by grydian** [comment]
Using QuantumStorage-1.12-4.6.2 with refinedstorage-1.6.12 and I cannot craft quantum disks using the crafter.  No recipe in JEI and it does nothing when you place a 64k storage disk in the crafter.
