### ISSUE TITLE
Quantum Storage Unit does not work anymore with 4.6.1

### ISSUE THREAD

**Issue by Roversword** [gigabit101/QuantumStorage#156]
Dear devs

I updated QuantumStorage in my modpack from QuantumStorage-1.12-4.6.0.jar to QuantumStorage-1.12-4.6.1.jar.
After that the already existing Quantum Storage units still worked, but those newly made could only hold 1 stack of an item...all subsequent stacks were "stuck" in the upper input box and never "fell" into the storage.
After downgrading to 4.6.0 again, the newly made units worked again.

My modpack runs on forge-1.12.2-14.23.4.2747-universal.jar (at the moment) and with about 66 other mods..inlcuding tinkersconstruct2, thermal expansion, AE2, industrial forgoing, etc.

Is there any more information you need to check this out?
Thanks

**Comment by Hotwire75** [comment]
Same issue here, upgraded from 4.4.9 to 4.6.1 with forge 14.23.4.2747 in a kitchen sink pack I've got going in MultiMC5, and existing/new empty ones can only be put into once... Unless using something like a hopper, AE2 storage bus, etc., which still works fine, and once you get more than a stack of an item in it, (ex. 17 eggs, 65 cobble, etc) then it's possible to insert into it manually again.

Soon as you pull it down to a single stack of an item though, any more put in manually just sits in the top slot like it does when you try to put something different in it until you use another method again..

**Comment by gigabit101** [comment]
Fixed in dev

**Comment by Nbome** [comment]
You released a non-working version 3 weeks ago and seem to have it all fixed in your dev which is nice and all but when are you planning to actually release your fix?

**Comment by gigabit101** [comment]
I am currently away for work and do not have the time to finish the update,
it will be done as soon as I have time to finish it

**Comment by gigabit101** [comment]
Fixed in QuantumStorage-1.12-4.6.2
