### ISSUE TITLE
Quantum Storage no longer working with FTB Revelation Mpdpack

### ISSUE THREAD

**Issue by jeddell** [gigabit101/QuantumStorage#159]
Hi, I downloaded this mod at V 4.5 and loaded it into Revelation 1.5 and it works really well. All the way up to version 2.2. It started having issues at Revelation 2.2 and is now crashing the Latest versions of Revelation (2.3), I downloaded the latest version of the mod (4.6.1). Made no difference. still crashed the game.  FYI

**Comment by gigabit101** [comment]
Fixed in dev

**Comment by gigabit101** [comment]
Fixed in QuantumStorage-1.12-4.6.2
