### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Luckyday84** [gigabit101/QuantumStorage#16]
Using version 1.8.9.2.0.0

http://pastebin.com/00bv1CZ4

**Comment by gigabit101** [comment]
try this version

**Comment by gigabit101** [comment]
https://www.dropbox.com/s/wqqtgax63xlv9z9/QuantumStorage-2.0.1.jar?dl=0

**Comment by gigabit101** [comment]
Install RebornCore
