### ISSUE TITLE
Mouse Tweaks scroll wheel and Quantum Storage Unit buglet

### ISSUE THREAD

**Issue by Hotwire75** [gigabit101/QuantumStorage#160]
Hi, when scrolling items out of the quantum storage unit via Mouse Tweaks, it will put one into the inventory(supposed to do this) and also have a stack minus one pulled out and connected to the mouse at the same time, preventing more being scrolled out of the storage until that stack-1 is put down somewhere(not supposed to do this).

Scrolling items into the QSU seems to work as expected.

Tested to happen in both my personal kitchen sink pack (~150 mods...) and in another instance with only the latest Forge, Mouse Tweaks, Quantum Storage, and Reborn Core installed.

Thanks

**Comment by gigabit101** [comment]
Ok, so the slot bottom slot is set to be output only.
If mouse tweaks is editing the slot contents as its being changed by the QSU this might cause the issue.
This is going to require some looking into.

This might also just be a syncing issue due to the inventory not being changed correctly.

**Comment by Hotwire75** [comment]
Not really knowing java at all I'm not entirely sure, but it looks like MT by default does it the simple way and just picks up a stack, shift clicks one into the other inventory, then attempts to put the rest back into what it came from... Which in this case by trying to drop the stack-1 back into the qsu output would mean it has nowhere to go and just winds up hanging there like it does.

MouseTweaks has an api... And there I got completely lost.
