### ISSUE TITLE
Quantum storage units get clogged and stop working - 2 bugs.

### ISSUE THREAD

**Issue by Nbome** [gigabit101/QuantumStorage#161]
Hi there,
I'm really sorry to file this issue but since you decided to make a core mod which replaces 'deep storage' your mod is essential to work and breaks the whole game if it doesn't - which is sadly the case... 

Bugs:
QSUs accept up to 3 different items - and put the items even into their lower 'storage' spot getting clogged up.

QSUs get clogged after the world is restarted (I think if they are fed items during the 'power-up').

To see this bug in action, I created a completely fresh world in creative using the 4.6.2. version of the mod and made a video: https://youtu.be/-1HHE3bP4lE

**Comment by Hotwire75** [comment]
First glance, it looks like there could be a load timing bug with AE2 storage busses... Like it is loading the busses and making them active before the filter has loaded in, instead of waiting on the filter to be ready first before letting the items flow.

**Comment by Nbome** [comment]
Yep - thats what I meant with "I think if they are fed items during the 'power-up'" - but I do not recall having this issue in the past using DSUs. Furthermore bug Nr. 1 indicates that there is generally something wrong with the way QSUs filter items.

**Comment by gigabit101** [comment]
I am currently working on rewriting this due to wanting to be able to add a lock to the QSU.
These issues will be resolved once this has been completed.
