### ISSUE TITLE
Quantum Tank duped

### ISSUE THREAD

**Issue by neoc666** [gigabit101/QuantumStorage#165]
Not sure when this happened, but I only crafted one tank and tested it and broke it and other blocks and after a while I noticed I had still a tank in my inventory when the tank was already placed in its position. I didn't put it in any other inventories while handling it. Can this happen because of desyncs (I'm playing strictly single player, with only the server necessary for a local minecraft game) or is it related to some of the other duping issues in the history of this mod?

**Comment by Cazadorsniper** [comment]
This also happens when place the tank or storage unit on the south side of a Astral Sorcery Marble Pillar

**Comment by gigabit101** [comment]
Nothing I can do about the Astral issue

**Comment by gigabit101** [comment]
This should also now be fixed.
