### ISSUE TITLE
Crash on Client Startup

### ISSUE THREAD

**Issue by rckymtnrfc** [gigabit101/QuantumStorage#17]
I'm seeing the following crash after adding your mod to my pack.

http://pastebin.com/jXWtknPY

**Comment by gigabit101** [comment]
@modmuss50

**Comment by modmuss50** [comment]
grr, ok I will take a look

**Comment by modmuss50** [comment]
wtf? https://github.com/modmuss50/JSON-Destroyer/blob/master/src/main/java/me/modmuss50/jsonDestroyer/client/ModelGenerator.java#L76

**Comment by modmuss50** [comment]
Can you try updating you reborncore version?

**Comment by rckymtnrfc** [comment]
Well shoot.  I didn't realize I had an older version of RebornCore.  I updated it and the client started up no problem.  Sorry about that.

Thanks for the help!
