### ISSUE TITLE
Quantum Storage still crashes with Reborncore on the new version just released on curseforge

### ISSUE THREAD

**Issue by ghost** [gigabit101/QuantumStorage#172]
https://paste.feed-the-beast.com/view/7b74ca5e

This just happen on the new updated on server a test server

**Comment by ghost** [comment]
@modmuss50

**Comment by ststeppat** [comment]
The some for me:

https://pastebin.com/HufjkZPG

**Comment by walker-dev** [comment]
+1

**Comment by modmuss50** [comment]
Humm, I may need to roll back the change in RC how ever RC has just had some big changes so it may not be totally stable. But it will be better than this.

Sorry about this.

**Comment by modmuss50** [comment]
Please try with: https://minecraft.curseforge.com/projects/reborncore/files/2645705

**Comment by ghost** [comment]
@modmuss50 still crashes on your new version, I more think its Quantumstorage and not Reborncore so just Quantum storage dev needs to just update his mod to work with your new changes and thinks will work

**Comment by ghost** [comment]
Mind you my crash is only server side, it works fine on client

**Comment by ststeppat** [comment]
the some for me, crash on Serverstart

**Comment by ghost** [comment]
Thanks, @modmuss50 and @boosterdev for working on getting a fix, can't wait for it to show up on curseforge and test it out

**Comment by walker-dev** [comment]
I tested it by recompiling the current version, it not longer crashes, it just need to be released

**Comment by jelaw21** [comment]
When can we expect a release?

**Comment by ghost** [comment]
That's what I have been wondering as well if we will see a update before the Holiday or not

**Comment by gigabit101** [comment]
Fixed in latest build, Blame @modmuss50 lol
