### ISSUE TITLE
QuantumStorage servercrash 

### ISSUE THREAD

**Issue by DarkEvoli** [gigabit101/QuantumStorage#173]
server crash after update.

https://pastebin.com/45PVfbQ0

**Comment by ghost** [comment]
@Tahrll your post is the same as this one https://github.com/gigabit101/QuantumStorage/issues/172

**Comment by pkmnfrk** [comment]
@TacticalUniverse for what it's worth, it's a different crash. Hopefully already resolved for the next version, though

**Comment by gigabit101** [comment]
fixed in latest build #Blame @modmuss50 :P
