### ISSUE TITLE
client side crash when interacting with quantum crafter

### ISSUE THREAD

**Issue by Heyo13579** [gigabit101/QuantumStorage#178]
The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: QuantumStorage.client.GuiBuilderQuantumStorage.isInRect(IIIIII)Z

just as the title says the error is listed above

this is on a server when i right click the quantum crater the client will crash but the server is fine

this is occurring on the latest version of 1.12.2 and only started happening after i updated to the recent reborn core update

**Comment by Heyo13579** [comment]
Update:

i reverted back to the previous version of reborn core server side and client side and everything is working correctly, ergo there seems to be an error with the recent reborn core update

**Comment by remclave** [comment]
I'm on a server using this mod and this issue is also happening with the Crating Machine:
(version 4.6.4)
(RebornCore Ver 3.13.0.400)

https://paste.dimdev.org/kumohemoko.mccrash

**Comment by gigabit101** [comment]
fixed in 4.6.5
