### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by freopt** [gigabit101/QuantumStorage#179]
I placed a unit and this happened. Latest mod version. Forge 14.23.5.2782
https://paste.dimdev.org/volosimebu.mccrash

EDIT:
It was when opening the gui. This happened when using the tank aswell.

**Comment by K-Hyouma** [comment]
Hello.
I also encountered a similar crash.
My friend told me that updating the "RebornCore" version is a problem.
I tried using "RebornCore-1.12.2-3.12.1.385" and it worked.

The cause was in changing the method name.
In RebornCore's GUIBuilder, "isInRect" was changed to "isPointInRect".

**Comment by gigabit101** [comment]
fixed in 4.6.5
