### ISSUE TITLE
Crash when opening gui

### ISSUE THREAD

**Issue by metaknight1992** [gigabit101/QuantumStorage#182]
Playing FTB Sky Adventure 1.4.0
Forge 14.23.5.2796
QuantumStorage-1.12-4.6.4
RebornCore-1.12.2-3.13.0.400-universal

Game freezes when I try to open either the QSU or the tank. oddly, minecraft does not crash immediately, but instead displays "not responding" several times for about a minute, then CTDing.

Crash Log for tank:
[https://pastebin.com/URHE80M3](url)

**Comment by gigabit101** [comment]
fixed in 4.6.5
