### ISSUE TITLE
GUI Crash saga continues!

### ISSUE THREAD

**Issue by metaknight1992** [gigabit101/QuantumStorage#184]
Hello again!
Playing FTB Sky Adventure 1.4.0
Forge 14.23.5.2796
QuantumStorage-1.12-4.6.5
RebornCore-1.12.2-3.13.0.402-universal

Still crashing when opening the various GUI, but it looks like a different cause at least...

[https://pastebin.com/qxLfnLp0](url)

Thanks for your hard work!

**Comment by gigabit101** [comment]
@drcrazy you failed :P

**Comment by modmuss50** [comment]
I can fix it if you want, @drcrazy lets not do any more breaking changes on 1.12

**Comment by gigabit101** [comment]
Plz do, I'm out for the day
