### ISSUE TITLE
Crash when trying to open GUI Quantum Tank

### ISSUE THREAD

**Issue by AbieTheFishman** [gigabit101/QuantumStorage#186]
Server shuts down when trying to open GUI.

Single player custom pack - I have two other packs and it is not an issue in those

The game crashed whilst rendering screen
The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: QuantumStorage.client.GuiBuilderQuantumStorage.isInRect(IIIIII)Z

Crash Report
https://pastebin.com/2uYqGqPM

**Comment by modmuss50** [comment]
Allready fixed, https://github.com/gigabit101/QuantumStorage/commit/8b6729bb094def5a67923b57f40edde904a4bf07

A new version needs pushing. In the future these changes will not be made to break things.
