### ISSUE TITLE
1.12.2 - Crash when right-clicking on a quantum tank

### ISSUE THREAD

**Issue by buleoer** [gigabit101/QuantumStorage#187]
Hi, I get this crash when I right-click on a quantum tank.
https://pastebin.com/7TYDhavf

**Comment by Foxbond** [comment]
+1

100% repro rate on Stoneblock pack, mod version 1.12-4.6.2

**Comment by Foxbond** [comment]
It does not happen on version 1.12-4.6.5 but there is no blue bar

**Comment by modmuss50** [comment]
Update your mods.
