### ISSUE TITLE
Performance drop when placing down Quantum Storage Unit

### ISSUE THREAD

**Issue by Kazzamkablam** [gigabit101/QuantumStorage#19]
It seems for whatever reason they seem to drop performance a lot, I placed down single one and my frame rate dropped around 20? And that was with empty one.

**Comment by gigabit101** [comment]
1.7.10 or 1.8.9 ??

**Comment by Kazzamkablam** [comment]
1.8.9

**Comment by gigabit101** [comment]
@modmuss50 any clue why Im using jsonDestroyer on this ?

**Comment by gigabit101** [comment]
I can't seem to reproduce this issue

**Comment by modmuss50** [comment]
Make sure you are using the latest version of reborn core as I did improve the performance of block models here: https://github.com/modmuss50/JSON-Destroyer/commit/a5827c772e46f81db1c3874fbfed95a127d912d0

**Comment by Kazzamkablam** [comment]
https://imgur.com/a1Zn6EM  This with it placed...

http://imgur.com/G3lyAFV This without it.

Tested with latest Reborncore

Client log: http://www.filedropper.com/logs_19

If it's any use.
