### ISSUE TITLE
Contents of Quantum Storage deleted when broken with Red Morningstar on modes.

### ISSUE THREAD

**Issue by ROSSO-D** [gigabit101/QuantumStorage#190]
## Bug Report
Using a ProjectE Red Morningstar on any other mode than Standard deletes the entire contents of a Quantum Storage unit.

## Steps to Reproduce (for bugs)
Break a Quantum Storage Unit with items inside using a Red Morningstar on Wideshot, Longshot or Tallshot mode.

https://clips.twitch.tv/PoliteInterestingSamosaDoggo

## Logs
* Client/Server Log: Not applicable
* Crash Log: Not applicable

## Client Information
* Modpack: Stoneblock (Developer sent me here)
* Server/LAN/Single Player: Single Player
* Optifine Installed:  No
* Shaders Enabled: No

Have been

**Comment by gigabit101** [comment]
Fixed in dev
