### ISSUE TITLE
[1.12.2 v4.6.7] Quantum Battery power duplication

### ISSUE THREAD

**Issue by wagyourtail** [gigabit101/QuantumStorage#194]
quantum batteries with same charge can stack meaning they can be used to duplicate power. charge batteries together then unstack and discharge separately.

![unknown](https://user-images.githubusercontent.com/6234704/54662155-4421de00-4a9a-11e9-9330-464fd2618636.png)

**Comment by gigabit101** [comment]
fixed in 4.6.8 already. :)
