### ISSUE TITLE
Massive bandwidth increase with Storage Barrels.

### ISSUE THREAD

**Issue by Mitsuma** [gigabit101/QuantumStorage#195]
Currently playing Project Ozone 3 and noticed a large increase in download bandwidth on my client. 
Seems like the cause QuantumStorage Barrels.

At first I was on version 4.6.6 because I was playing the last version of the pack, then I read that 4.6.7 supposedly fixed some network issues.
After updating to the latest 4.6.8 the issue still persists, or I think its still higher then normal, at the time of writing the server just restarted, so Im not sure if that factors into anything or not.

First time I noticed it, v4.6.6:
![Taskmgr_2019-04-02_21-10-42](https://user-images.githubusercontent.com/8568089/55436242-0ba2f980-559c-11e9-87e3-dc786e8635bb.png)

Current usage as I'm writing this, v4.6.8: 
![Taskmgr_2019-04-02_23-07-26](https://user-images.githubusercontent.com/8568089/55436272-24abaa80-559c-11e9-825c-29c96e69fe6c.png)

My setup is probably more on the extreme side: 
![javaw_2019-04-02_23-08-04](https://user-images.githubusercontent.com/8568089/55436305-368d4d80-559c-11e9-9bc7-a07384fda89c.png)
Each of them does have a AE2 Storage Bus behind them. 
A farm of one crop per barrel feeds them over the AE2 network, its not mega fast but not too slow.

In terms of troubleshooting I did a few things:
- The bandwidth increase is specific to being in render distance to the storage barrels.
- Being in other dimensions or just out of range of the barrels (when the items inside don't render but you can still see the barrels) drops bandwidth to normal levels
- I removed all AE2 storage busses, no change in bandwidth usage
- Its not the mentioned farm either as removing those or disabling the farmer won't change anything either.
- I removed all barrels in the copied world and bandwidth went back to normal.

I could work around this in plenty of ways, putting it out of render range, using YABBA barrels, using big-preformated AE2 disks.  
Would love to avoid this though, with the like 100+ types of essences and stuff thats a bit of work.

**Comment by gigabit101** [comment]
The units only send a packet when the item in the inventory changes, I am going to be releasing a new build soon that will only send the packet when the GUI is open.

This will resolve this but will also mean that the render might not function until you open the GUI.
I plan on adding a delay to send a packet every little while to update the render if needed but will take some time to add.
