### ISSUE TITLE
Overflow of quantum storage disk

### ISSUE THREAD

**Issue by bufu1337** [gigabit101/QuantumStorage#196]
Hello,
I am using an older version (4.4.6) and i dont know if it is already fixed, but i cant find it in the changelogs.

Problem: 
i am generating water from an infinite pool and storing it to a quantum fluid disk.
Of course the disk is filled after a time, but then he continues storing water and the disk switches from maximum size to negative size. After this overflow the refined storage fluid matrix displays water wrongly. It starts at zero everytime i access the matrix.
I tried it with an quantum storage disk for items and cobblestone generators and had the same issue.

**Comment by gigabit101** [comment]
Hmm, I have an idea what is causing this, Will need to dig into it when I get some free time.
