### ISSUE TITLE
[1.12][4.6.8] Creative Storage Upgrade Broken?

### ISSUE THREAD

**Issue by ryantheleach** [gigabit101/QuantumStorage#197]
Quantum Storage 4.6.8 - 1.12

In a single player creative world, placing a QSU down, with a single stone block, then shift right clicking with the creative upgrade seems to do nothing.

**Comment by gigabit101** [comment]
Forgot to reimplement this when I fixed some other issues in the code base.
I will get this fixed once I get some free time.
