### ISSUE TITLE
TPS lag

### ISSUE THREAD

**Issue by Machine-Maker** [gigabit101/QuantumStorage#198]
I get massive amounts of TPS lag when I setup ~48 quantum storage units to hold essences from mystical agriculture. As soon as I remove them, the lag is gone. I am playing PO3 on a server. 

(if this is the issue fixed in 4.6.7 then just let me know and close it)

MC 1.12.2
Mod Version: 4.6.6

**Comment by gigabit101** [comment]
This has already been resolved in newer builds
