### ISSUE TITLE
Incompatibility with Thaumcraft 5 golems

### ISSUE THREAD

**Issue by runfalk** [gigabit101/QuantumStorage#20]
This is somewhat related to the recently fixed bug #18.

If I use a Thaumcraft 5 golem with a storage seal it will destroy the items it puts in the QSU. If the golem puts in less than a stack (64) it won't increase the contents of the QSU at all. If it tries an entire stack it will increase by one item.

I am not sure of whether it should be reported here or on the Thaumcraft 5 issue tracker.

The workaround for now is to place an hopper on top which the golem puts items into.

**Comment by gigabit101** [comment]
I will look into it

**Comment by Keridos** [comment]
@runfalk can you test with the latest curseforge build please?

**Comment by runfalk** [comment]
I don't think I still have my modpack available. It was "homegrown", and I stopped playing that save months ago. If anyone else could verify that would be great.
