### ISSUE TITLE
Duplication / Item deletion

### ISSUE THREAD

**Issue by xplatform-dev** [gigabit101/QuantumStorage#204]
If you were to use a hopper to insert an item into the quantum storage unit that is not the same type as the quantum storage unit than the item is deleted however the count is increased by 1 for each item the hopper puts into the unit. Thus turning sticks into diamonds.
The quantum storage unit SHOULD not accept the input from the hopper, in the same way the furnace doesn't accept redstone from the rear.

Recreation:
(ONE)
1: place 1 iron block in the quantum storage unit (it should show an iron block)
2: place 1 cobble stone in the quantum storage unit.
3: pull out 2 iron blocks... break 1 block into 81 iron nuggets.
4: place 1 iron block in the quantum storage unit (it should show an iron block)
5: place in 81 iron nuggets.
6: pull out 64 iron blocks and 18 iron nuggets.
7: break 1 iron block down to 81 nuggets (99 total).
8: place 1 iron block in the quantum storage unit (it should show an iron block)
9: place in 64 iron nuggets.
10: place 1 more iron block in the quantum storage unit.
11: place the remaining 35 nuggets in the quantum storage unit. (There should be 101 items in the storage unit -- all of them are iron blocks).  Pull them all out...
(TWO)
12: Break down as many blocks as you can into nuggets.
13: Place 1 iron block in the quantum storage unit.
14: Place 63 iron nuggets in the quantum storage unit.
15: Place 1 iron block in the storage unit.
16: Place another 63 nuggets in the storage unit.
17: I closed out of the storage unit's GUI here - but glancing at the code it doesn't matter.
18: take out half a stack (32) of the unit by right clicking and place it back in the storage unit.
19: While the device is still filling up the stack, empty as many nuggets as you can into the unit.
20: Place the rest of your inventory into the quantum storage unit.
21: Pull out 2k+ iron blocks.

Not bad for 29 wood planks, 11 cobblestone, 1 coal, and 7 iron ore/ingots.

Works with non-stackable items as well.

It does not work with other blocks added by this mod.

**Comment by dfisheritp** [comment]
Should also note, that a hopper isn't actually needed to do this. (I just hadn't actually tried before posting)

**Comment by dfisheritp** [comment]
It seems to be associated with item stacks.
I can place 1 iron block in the unit and then place 64 iron ingots in and I'll be left with a full stack of iron blocks and 1 iron ingot (after I pull out the stack of iron blocks).
Similarly, if I place 1 iron block and 63 iron ingots followed by another iron block and another 63 ingots I have 128 iron blocks ready to be pulled out.

**Comment by gigabit101** [comment]
What version of the mod are you using?

**Comment by Mystogrigen** [comment]
I have this same issue with shift-clicking items into the QSU.

QuantumStorage-1.14.4-5.0.0.jar

**Comment by xplatform-dev** [comment]
@gigabit101 Sorry about delay, Mystogrigen gave good information on the version but I think I gave enough to reproduce in whatever version you wanted to try.

**Comment by Reignofmagic** [comment]
Adding onto this in version QuantumStorage-1.14.4-5.0.0, you can also just manually put in any item for the deletion/duplication issue

**Comment by gigabit101** [comment]
fixed in the latest build
