### ISSUE TITLE
javafml 28 error with forge 28.1.1

### ISSUE THREAD

**Issue by raziel23x** [gigabit101/QuantumStorage#207]
![image](https://user-images.githubusercontent.com/441966/64901729-c9add180-d66a-11e9-930e-36a9f6119422.png)

Here are 2 pull request i did to fix the issue
https://github.com/gigabit101/QuantumStorage/pull/205
https://github.com/gigabit101/QuantumStorage/pull/206

**Comment by DvlDddy** [comment]
Is there a way to fix this on the server side?  Getting this same error when trying to start up.

**Comment by raziel23x** [comment]
open up the jar file and edit this file  src/main/resources/META-INF/mods.toml and just add a , to loaderVersion="[28]" #mandatory to change it to this loaderVersion="[28,]" #mandatory

**Comment by gigabit101** [comment]
fixed in latest build
