### ISSUE TITLE
[1.14.4] QSU will not store any subsequent items after seeding it with initial items.

### ISSUE THREAD

**Issue by fuzzyweapon** [gigabit101/QuantumStorage#209]
MC:  1.14.4
Forge:  28.1.56
QS:  5.0.1

----

### Steps
1.  Put down a freshly crafted QSU (or one from creative).
2.  Right click the QSU to bring up the GUI.
3.  Put some stone into the QSU (by manually clicking from inventory to QSU input or by shift-clicking).
4.  Put some stone into the QSU (by manually clicking from inventory to QSU input or by shift-clicking).
5.  Observe totals.

### Observed Results
The QSU total never climbs after the initial deposit.  The method does not matter.  The item does not matter.  This is destructive.  It consumes the amount deposited and the player never gets it back.  They only ever get the initial deposit back.

This was tested with white wool blocks, spruce planks, and stones in individual tests.
This was tested by manually transferring into the QSU input box, by shift-clicking into the QSU input box.
This was tested by making the first deposit, backing out, going back into the GUI, and making a second deposit.
In all cases, this bug occurred.

**Comment by gigabit101** [comment]
looking at the changes to the code I made this might be working but not syncing the new value to the client, Can you attempt to log out and back into the world after this and see if the issue continues?

**Comment by gigabit101** [comment]
fixed in 5.0.2
