### ISSUE TITLE
doesn't work properly with Ender IO item conduit

### ISSUE THREAD

**Issue by LordHellscream** [gigabit101/QuantumStorage#21]
Attempting to push additional stack of items to the quantum storage doesn't work. It will only hold 64 items and any additional items being pumped in from Ender IO item conduit simply disappears.

this is using the 1.9.4 version (mod version latest as of June 13th)

**Comment by modmuss50** [comment]
Update Reborn core and try again? I pushed a version yesterday

**Comment by RealGrep** [comment]
Just noticed the same exact issue, so I of course came to find the bug tracker. I have RebornCore-1.9.4-2.5.4.47-universal.jar, which seems to be the latest available. Also, QuantumStorage-1.9.4-3.1.0.jar. So don't think that fixed it.

**Comment by modmuss50** [comment]
Ok, when either me or @gigabit101 has the chance we will look into this issue.

**Comment by gigabit101** [comment]
yeah I think I need to switch this to the new inv system aswell as rewrite how the inventory works

**Comment by Keridos** [comment]
What is even worse is that the items simply disappear btw.

**Comment by gigabit101** [comment]
Yes this is because capabilities again I have already added them in the
next 1.9.4 and 1.10.2 version just fixing up the last of the new tank
system

**Comment by Keridos** [comment]
You might take want to take a look at some of the fixes I wrote. Especially the sync entitities code is far more efficient for the DSU.

**Comment by gigabit101** [comment]
Yeah I will take a look i might end up rewriting them anyway I have a few
ideas already for improvements and changes I want to make

**Comment by nini84** [comment]
Same with Refined Storage and Network Storage, they go up to 64 and then the mechanics of quantum chest shows it has 65. If you add more it gets deleted, and it always ads one more then it really has, Also using Enderio Panel or any storage mod with Panel that is connected to a quantum chest via interface is duping items, When i place some items in the quantum chest like 4 ingots it shows it has 5 (when it has 4 really) and just shift clicking all at once i will get 5 ingots so i just made one for free. Can be repeated.

**Comment by Keridos** [comment]
I have a working beta version here, @gigabit101 you could clone my repository (the fork) build it and upload it to curseforge while you are rewriting stuff, so people can enjoy the mod for now.

**Comment by gigabit101** [comment]
@Keridos TBH I do not have alot of time to work on this atm this weekend I am in the #ModIngTrials and I work most of the week.
Do you want to be part of this mod I will give you repo access and curse access if you want to?

**Comment by Keridos** [comment]
Yeah, you can do that. Thanks for the invitation.

**Comment by gigabit101** [comment]
@Keridos invite sent

**Comment by gigabit101** [comment]
@Keridos curse name please

**Comment by gigabit101** [comment]
@Keridos I think I got you on curse but not sure can you confirm I added you to QuantumStorage

**Comment by Keridos** [comment]
All good!
