### ISSUE TITLE
Issue When Shift Clicking Items Into Container

### ISSUE THREAD

**Issue by DizzyDJW** [gigabit101/QuantumStorage#211]
I pre-define item stacks in the container, (in order to shift click items into it and have them go where I've already placed one), but with these containers the shift+clicked items go to the first available empty slot rather than say a slot with only 20 items in it.

**Comment by gigabit101** [comment]
What Minecraft version are you having this issue with? I only as because the entire mod got rewritten in 1.14

**Comment by DizzyDJW** [comment]
Minecraft version 1.12.2
Forge version 14.23.5.2847

It's in Project Ozone 3 Modpack

It is also updated to latest version 4.7.0
