### ISSUE TITLE
Game crashes when opening the Quantumtank

### ISSUE THREAD

**Issue by simonwoegerb** [gigabit101/QuantumStorage#214]
Hi, I was playing FTB Sky Adventures and built a mobfarm with Industral Foregoing. Wanted to use QS for the storing of the Essence. Connected both with an EnderIO Ender Fluid Conduit. Opened the Tank and my game crashed.

Here is the link to the complete Log made by the game:
https://paste.ee/p/TyaxR

**Comment by gigabit101** [comment]
Update to the latest version
