### ISSUE TITLE
Multiblock troubles with inputting/outputting.

### ISSUE THREAD

**Issue by Lemon-Lord** [gigabit101/QuantumStorage#215]
Currently playing in the modpack _Project Ozone 3 - Kappa Mode_ and have a 4x4x4 (6x6x6 with casing) QuantumStorage multi-block. The issue is that some items just do not register as being inside the chest unless I physically go into the chest and take them out. I only recently ran into this problem and it was working, to my knowledge, fine, up until that point. It seems that whenever I input an item into the system (through non-player interactions like hoppers or item conduits), every slot preceding it gets registered if they weren't already but any slots afterwards are still not recognised by any methods of extraction I've found. I've tried item conduits, hoppers, various applied energistics I/O methods and they have all seemed to conclude that the item does not exist within the multiblock's inventory. I think that if I were to break the 64 Storage Unit blocks and go through the agonising process of putting all ~1000 item stacks back into the block, it would work again but this bug has set me back quite a bit. It's possible that the deregistering bug occurred when I piped all of 1 type of item out of the system to put them elsewhere. I have screenshots if you require proof.

**Comment by gigabit101** [comment]
This has been removed in 1.14+ and 1.12 is no longer supported
