### ISSUE TITLE
left clicking destroy quantum storage, and disappear

### ISSUE THREAD

**Issue by eloe79** [gigabit101/QuantumStorage#216]
not sure if this was intended but when left clicking, destroy totally quantum storage box and nothing drops, seems like some kind of bug, as dont believe it was intended?
also dont seems to create any config file ?

Minecraft Version: 1.15.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_241, Oracle Corporation
ModLauncher: 5.0.0-milestone.4+67+b1a340b
Forge: net.minecraftforge:31.1.27
QuantumStorage-1.15.2-5.1.0.jar

**Comment by gigabit101** [comment]
Fixed in 5.1.1.

**Comment by eloe79** [comment]
cinfirmed, btw, fix have also deleted all stuff that was in it, justgreat :(
