### ISSUE TITLE
Block lags game

### ISSUE THREAD

**Issue by DoughnutDev** [gigabit101/QuantumStorage#22]
When you are in the same chunk as the Quantum Storage Unit your FPS will drop so much that it is almost unplayable. I am not sure what is causing this sense the block itself does not have any animation or anything.

Minecraft: 1.9.4
Mods Version: 1.9.4-3.1.0
Forge: 12.17.0.1966

**Comment by RealGrep** [comment]
Would probably be helpful if you supplied the version of QuantumStorage you're using, as well as Minecraft and Forge. A log file from when this happens may or may not be useful as well. :)

**Comment by DoughnutDev** [comment]
@RealGrep The log does not move when you place it. I try finding something in there already.

**Comment by gigabit101** [comment]
hmm I will take a look into this later

**Comment by GrumpyChunks** [comment]
Seeing this exact same problem with version 3.0.0 of the mod. FPS drops from 60 to <10 fps when the block is placed, when I break the block, FPS returns to normal.

**Comment by gigabit101** [comment]
its a simple block and I can not reproduce this bug http://imgur.com/Aqkesav

**Comment by gigabit101** [comment]
![aqkesav](https://cloud.githubusercontent.com/assets/5615438/16932645/9a1e986c-4d3f-11e6-8ce7-b0fb51ad5877.png)

**Comment by gigabit101** [comment]
I am not having this issue at all so...

**Comment by gigabit101** [comment]
its a basic block for rendering so is should cost the same as stone to render as for the tile its all done server side so...

**Comment by GrumpyChunks** [comment]
I've discovered something that might help diagnose.

This one, was placed with only a single exposed face, FPS drops from 60 to 10

![2016-07-18_23 43 58](https://cloud.githubusercontent.com/assets/1747010/16932942/ce76c9b6-4d41-11e6-8a56-9c3cd7511ac7.png)

Same position, just broke the block, back to 60 FPS

![2016-07-18_23 44 06](https://cloud.githubusercontent.com/assets/1747010/16932957/ec832f62-4d41-11e6-8682-02ca95b98853.png)

This time, placed the block with sides not touching anything, and FPS only drops to 40-50.

![2016-07-18_23 44 16](https://cloud.githubusercontent.com/assets/1747010/16932973/068e7b5a-4d42-11e6-949f-eefc03714dc9.png)

This behaviour is consistent and can easily be repeated. For mod list, see [here](http://minecraft.curseforge.com/projects/puretech/relations/dependencies)

**Comment by GrumpyChunks** [comment]
It's definitely caused by the rendering as the shift F3 graph shows the gameRenderer go wild when the game goes laggy. Hope this helps! For what it's worth, I'm playing on a (personal) dedicated server, Java 8 x64. 3GB allocated to the server and 3.5GB allocated to the client.

**Comment by BootyToast** [comment]
I'm having the same issue as well. I have the latest version of RebornCore and QuantumStorage. It's worth noting that the reason it may be hard to reproduce this is because storage units with more items in them seem to lag more.

**Comment by GrumpyChunks** [comment]
Just FYI, I've not yet stored a single item in the block, as it instantly lagged.

**Comment by BootyToast** [comment]
This is impossible to reproduce in a new or a vacant part of your world, but when placed in an area populated with machines it's instantly noticeable. Will try and update with screenshots later.

**Comment by DoughnutDev** [comment]
Yeah, I am still having the issue in my server with just placing it in the
world with no items and it will lag to holy lag.

**Comment by Keridos** [comment]
Having the same issue here, forge-1.10.2-12.18.1.2022, RebornCore-1.10.2-2.6.2.15, QuantumStorage-1.9.4-3.1.0. After about 30 seconds worth of profiling I can say what the issue is btw. This block seems to cause chunk rerenders every tick.

You should be able to just merge this and it should fix the bug, if any syncing bugs arrive you need to deal with them seperately. The code I deleted caused a chunk rerender and that chunk rerender caused another data packet to arrive causing another chunk update. Basically the complete chunk that this block stood in was rerendered every tick, causing the massive drop. Since the FPS drop depends on the amount of blocks in the general area this was probably why most people did not see much drops when placed in an empty/worldgen chunk and big fps drop when placed in people's bases.

**Comment by gigabit101** [comment]
3.1.1 is now on curse issue should now be resolved
