### ISSUE TITLE
Ehm

### ISSUE THREAD

**Issue by hnrosie520** [gigabit101/QuantumStorage#220]
For the 1.15.2 Many things seem to be missing. Quantum Disk Refind Storage. Or quantum battery. Do these things still come?

**Comment by gigabit101** [comment]
They will be back in an update, I have already re-added the battery in dev and the disk will come back soon as well

**Comment by hnrosie520** [comment]
Thank You for your Great Work. A Love this Mod. :3

**Comment by hnrosie520** [comment]
When do you think the update will come. I know that takes time. Only in 1.15.2 Quantum Disk is not the same? Can You Support?

**Comment by gigabit101** [comment]
Currently, I have no idea I have many other projects on the go as well as work, Can I ask what you are looking to see back first?

**Comment by hnrosie520** [comment]
Most importantly, the most important Quantum Disk and Quantum Storage. Recipe is wrong in 1.15.2. Quantum tank is also very important. The backpacks can be found in many other mods. The most important thing is the Quantum Disk with the recipe as before . Have to say really incredible work again. Any engineering mod working should use this one. Do you have Paypal or Pateron?

**Comment by gigabit101** [comment]
The tank has already been re-added in dev and will be back in the next release as well as the disk as this is not a difficult thing to add back however I am not sure that the recipe will be the same at this time as the machine I added in the last version to create this item was kind of a bust as it was only used for the one recipe, If you have any ideas for a better recipe or way or creating this item please do let me know and if I like the idea it might just make it into the mod.

You can find a donate button at the top of my curse pages as well as a Patreon link in the description for my of my mods.

**Comment by hnrosie520** [comment]
I forgot to mention the Quantum Storage battery. The Quantum Storage Disk recipe was a good thing. Also that you had to build first so that you can build it first. But if you want to change it, I would make it a little more difficult. 4x Quantum Storage you need. I would take away the function of the crates that you can store items on it. Sorry for my Bad Englisch.
