### ISSUE TITLE
[1.16.1] Storage crate gets ESP when placed against a wall

### ISSUE THREAD

**Issue by C0rn3j** [gigabit101/QuantumStorage#227]
```
QuantumStorage-1.16.1-5.2.0.jar
Forge 32.0.106 
```

![image](https://user-images.githubusercontent.com/1641362/89436933-34667080-d747-11ea-891b-4820182c61bd.png)

The small hole sees through walls if the storage crate is placed against one

**Comment by gigabit101** [comment]
fixed in newer builds
