### ISSUE TITLE
"Missing Lisence Information" error code in Minecraft

### ISSUE THREAD

**Issue by gumiEN** [gigabit101/QuantumStorage#230]
So when launching minecraft it gives me the error, I am using minecraft 1.16.3 and forge latest forge 1.16.3 - 34.1.24 as required by one of the mods. I have tried using previous and the up to date quantum storage however it doesn't seem to be getting along well :/ Any tips would be useful!

**Comment by gigabit101** [comment]
Wait for a 1.16.3 release
