### ISSUE TITLE
[1.16.3/4] Crate/Bag Inventory Size Balance/Suggestions 

### ISSUE THREAD

**Issue by JeffersonDoan** [gigabit101/QuantumStorage#232]
Finally one of my favorite storage mods has made it to 1.16.3+! I love the addition of the Controller and I'm very happy to see the Quantum Tank finally return. Browsing through the crates and bags I'd like to hear your thoughts on changing the inventory sizes.

**Currently**
Iron Crate: 6x4 (36 slots)
Gold Crate: 9x6 (54 slots)
Diamond Crate: 12x9 (108 slots)
Quantum Bag: 13x8 (104 slots)

**Suggested**
Iron Crate: 6x6 (54 slots)
Gold Crate: 9x9 (81 slots)
Diamond Crate: _No change_
Quantum Bag: 12x9 (108 slots - to match the Diamond Crate used for crafting)

This would bring the crates more in line with other chest/barrel storage mods, and crafting the quantum bag wouldn't result in a net loss of space.

Perhaps also the default recipe of the iron crate could be changed to use planks across the top and bottom with a chest in the middle? The would match the other crate recipes, and result in a gain of storage space instead of a loss (3 chests = 81 slots.)

**Comment by gigabit101** [comment]
I will not be changing the inventory sizes of anything at this time as it would cause issues with loading existing inventories.
