### ISSUE TITLE
Quantum controller and Refined Storage (1.16.4)

### ISSUE THREAD

**Issue by sirben99** [gigabit101/QuantumStorage#233]
Hey!

I have a problem with the Quantum controller and the interaction with Refined Storage external inventory.

For the controller it self its very, how do you say, fineky to use. If you use the hammer with link mode it should be linked to the quantum storage. But there is a very poor indication of wich one is linked. You do get LINK: True text, but if you try to link again it says link false. This is fine but if you keep linking it the text says false every time. And to my testing it doesent accualy de-link the storage. A way to see what storages u have with a gui would be a godsent to this problem. I really dislike the lack of instruction in this mod. Im fine with some self discovery but to craft a block that doesent have any interface or repesantation of how it works is pain when u just want to manage ur storages. Also fluid storages dont link at all.

Now to the refined storage. It seems that i can link 3 quantum storages to the controller and everything works. The external storage sends items and i can withdraw them. But when i try to link more it just stops working. I spend at least an hour to see why it dint work and coudnt find a proper reason. It could be external storages problem but since three storages work so i dont think its that.

I dont mean to sound, well, mean and i hope this would give some constructive criticism, since this is the only mod for this version that adds one of my faforite features from minefactory reloaded and older versions of industrial foregoing. If these issues get fixed/added, this could be the best deep storage mod, but for now it lacks a bit polish. Also sorry for poor english im not a native speaker.

Cheers!
Ben

**Comment by pd200** [comment]
The same problems with the ME Storage Bus of Applied Energistc 2.

I linked some quantumUnit, the problem occurs when i started the autocrafting, the item stored in quantumUnit aren't accessible to Applied, but it only concerns autocrafting, as when I manually take the items everything works and also when they are inserted in the quantum unit

**Comment by DrPinguin98** [comment]
Same here :/

**Comment by gigabit101** [comment]
1.16.4 is no longer supported
