### ISSUE TITLE
Bag in itself.

### ISSUE THREAD

**Issue by shamilhaqeem** [gigabit101/QuantumStorage#235]
Encountered in the Enigmatica 6 Modpack (1.16.4).
You can move the quantum bag into it's inventory if you use the hotbar buttons.
https://i.nuuls.com/x308E.gif

**Comment by cryobane** [comment]
Can duplicate same issue in Direwolf20 1.16. Bag moves into its own inventory, instantly closes and disappears.

**Comment by TychoHenzen** [comment]
same in TNP limitless (QS 5.3.0 Alpha5)

**Comment by Kaperkapeike** [comment]
has anyone already found a solution to get the items again?
