### ISSUE TITLE
Backpacks Not Syncing Correctly In 1.16.4

### ISSUE THREAD

**Issue by ChrisLTheNerd** [gigabit101/QuantumStorage#237]
The backpacks seem to be having trouble syncing because I got a backpack in creative put stuff in it grabbed another of the same color and it worked fine. But then I tried adding another item in one of the backpack and it doesn't sync anymore. It even worst in survival because it doesn't sync at all. This is in version 1.16.4-5.3.0 of the mod.

Here is an example in creative

https://user-images.githubusercontent.com/50182206/103470820-4f183200-4d45-11eb-956b-b8073840eb6f.mp4

Here is an example in survival 

https://user-images.githubusercontent.com/50182206/103471156-83422180-4d4a-11eb-907f-ae480953254d.mp4

**Comment by gigabit101** [comment]
This is correct, Bags currently no longer sync, This will be returning soon as an upgrade to the bag
