### ISSUE TITLE
[1.16.4] Dupe Bug

### ISSUE THREAD

**Issue by NielsPilgaard** [gigabit101/QuantumStorage#239]
The GUI for Crates is not closed when the Crate is broken, resulting in the ability to dupe anything.
Video: https://user-images.githubusercontent.com/77418462/104525454-35d97600-55ce-11eb-9fad-7bfa2aa1a0d3.mp4

### Versions
- QuantumStorage-1.16.4-5.3.0
- Forge-1.16.4-35.1.29

**Comment by Sunekaer** [comment]
Same with Quantum Storage Unit

**Comment by gigabit101** [comment]
1.16.4 is no longer supported
