### ISSUE TITLE
[BUG]1.16.5 Direwolf20 pack deletion of bag

### ISSUE THREAD

**Issue by MasterIPI** [gigabit101/QuantumStorage#241]
Quantum bag just disappeared from my inventory with all items and when I tried to get another one through jei, it didn't have all my items.
All I can say is that I pressed 2-4 keys on my keyboard by accident in the middle part (from d to h) when I opened my bag, then it closed and disappeared from my inventory.

**Comment by MasterIPI** [comment]
just figured it out - it disappears when you open the bag and simultaneously press hotkey for swapping item with offhand. It worked on 3 or 4th time I did that.

**Comment by gigabit101** [comment]
Bags do not retain their inventory currently, This is a planned upgrade for the bags in the next version
