### ISSUE TITLE
Quantum Bag disappears if you open bag and swap with empty slot inside bag

### ISSUE THREAD

**Issue by TronWoWGamer** [gigabit101/QuantumStorage#242]
Steps to Reproduce

1. Create Quantum Bag
2. Place bag on hotbar and select bag (say slot #7)
3. Open bag from hotbar
4. Hover mouse over empty slot in bag and hit the hotbar number for the bag (say slot 7)

Bag closes and disappears.

**Comment by DerHope** [comment]
I'm playing version 1.16.4-5.3.0 (in the Direwolf20 FTB modpack) 
I cannot only duplicate this bug, but add to the description: the bug also occurs when ANY slot (emtpy or not) in the bag is moved via hotkey to the hotbar slot of the bag.

This has caused SERIOUS loss of inventory at least 5 times now and could only be "solved" by backstepping to a backup!
PLEASE fix this issue. It would be much appreciated! 
Thanks!

**Comment by Ethan23p** [comment]
Very severe ):

**Comment by gigabit101** [comment]
Once I figure out how to stop this from happening it will be fixed, It's odd that this does not respect what items are allowed in the slot...

**Comment by BrettMoan** [comment]
this bit me HARD on a multiplayer survival server tonight, and now i've got to see if an admin can restore my player data from a a backup...

I was only using these bag cause the curseforge says they are linked to player data by bag color, which may be true in older version but IS NOT true in the 1.16.5

if you can't fix this bug, then get the bags being linked fixed cause i was very upset to find out out that i can't juyst make another quantum bag to restore my items.

**Comment by gigabit101** [comment]
1.16.4 is no longer supported
