### ISSUE TITLE
Bag not sorting properly

### ISSUE THREAD

**Issue by Breadabix** [gigabit101/QuantumStorage#244]
When I try and sort a bag with inventory tweaks it does not sort how you would expect. This is a screenshot of the contents of a bag that has been sorted using middle mouse button and the default sorting button on the right. As you can see there are still stacks of white glazed terracotta throughout the bag not in 1 sorted line.
![2021-06-25_14 29 20](https://user-images.githubusercontent.com/19786108/123431973-c5de0b80-d5c1-11eb-80ca-a2142fecf55f.png)

Forge: 14.23.5.2855
QuantumStorage: 4.7.0
InventoryTweaks: 1.64+dev.151

I have tried multiple versions of both mods and I havnt found a combination that the sorting is normal.

**Comment by Nexans20** [comment]
If this issue persists in the latest version of minecraft it will be looked at. However 1.12.2 will not be looked at anymore. QS had 2 complete rewrites since 1.12.2

**Comment by Breadabix** [comment]
Damn, shame as 1.12 is played a lot but ¯\_(ツ)_/¯

**Comment by mellamokb** [comment]
@Breadabix Ran into this same issue with 1.12 modpack Project Ozone 3.  So used CoPilot to generate a fix, which seems to work.  It is unofficial but you (or anyone else that stumbles on this same issue), feel free to use this replacement jar (or build it yourself): https://github.com/mellamokb/inventory-tweaks/releases/tag/v1.64-quantumfix.2
