### ISSUE TITLE
Duplication bug in 1.16

### ISSUE THREAD

**Issue by jacoballen1** [gigabit101/QuantumStorage#246]
Storage crates do not close the inventory for all players that are viewing if the crate is broken, allowing the viewing players to still pull all of the existing items out.

Replicating this requires two players, one to break the crate and one to view the crate as it is being broken. Once the crate is broken, pull any item out and exit the menu. Once the viewer has exited the menu, have the other player place the crate back down.

**Comment by gigabit101** [comment]
1.16.4 is no longer supported
