### ISSUE TITLE
Unable to re-link or to link new storage units after un-linking

### ISSUE THREAD

**Issue by qw2341** [gigabit101/QuantumStorage#247]
Game Version: FTB Direwolf20 1.16 v1.12.0

Issue: After unlinking a storage unit by right clicking on the controller, it cannot be re-linked, and any attempts to link a new storage unit will be "connected: false" and not connected (as not showing up in refined storage)

**Comment by qw2341** [comment]
A temporary workaround I found is to place down a new controller or break and replace the old controller (which will clear all links)

**Comment by gigabit101** [comment]
1.16.4 is no longer supported
