### ISSUE TITLE
Quantum Storage Unit Glass does not render

### ISSUE THREAD

**Issue by addandias** [gigabit101/QuantumStorage#250]
Hello, the glass of the quantum storage unit does not render, I have already tried to check on the internet and in the mod settings but I have not found any answer.

Minecraft 1.12.2
OptiFine_1.12.2_HD_U_G5
QuantumStorage-1.12-4.7.0
Modpack: Project ozone 3

![sc1](https://user-images.githubusercontent.com/81536003/222964782-bb5f91da-eb0f-4c92-a385-2c32b98b2c81.png)

**Comment by gigabit101** [comment]
Optifine breaks the glass render
