### ISSUE TITLE
No quantum storage disk

### ISSUE THREAD

**Issue by NetanelGuber** [gigabit101/QuantumStorage#251]
when I use the mod I don't see the quantum storage disk when I search for it in the JEI, I don't even see it in general and I don't know what to do

![image](https://user-images.githubusercontent.com/83191711/232481661-ceff982d-699d-4ec6-a375-8504c6bf6a8a.png)
![image](https://user-images.githubusercontent.com/83191711/232481683-4c995a21-cff8-47ec-85a9-2a5a1bbfc3b0.png)

those are all the items I see when I search @quantum

I am using version 1.12.2

**Comment by gigabit101** [comment]
It was not added until later than 1.12.2

**Comment by NetanelGuber** [comment]
> It was not added until later than 1.12.2

is there any way to add it to 1.12.2 or no?
