### ISSUE TITLE
Quantum Storage Unit deletes items when broken

### ISSUE THREAD

**Issue by psychofad** [gigabit101/QuantumStorage#28]
I know it used to keep its inventory when you broke it with a pickaxe, but it seems something has changed.  If you place one down, fill it with items, then use a pickaxe to break it, it does not drop any items or store them, they are just deleted from the world and you are left holding an empty storage unit.  I am able to move them around with the Moving Wand from NotEnoughWands and they retain their inventory, but apparently the data is not being written to the item when it is broken and it does not respond to any wrenching methods I have tried.

QuantumStorage-1.10.2-3.2.2
RebornCore-1.10.2-2.7.1.38-universal
forge-1.10.2-12.18.1.2086

**Comment by gigabit101** [comment]
update to 3.2.3
