### ISSUE TITLE
Packet exception spam from tile entities far away

### ISSUE THREAD

**Issue by BlayTheNinth** [gigabit101/QuantumStorage#30]
On a server I'm at 564, 65, -567 and am receiving update packets from a Quantum Storage Unit at 1099, 67, 275 (note the large distance between), resulting in an [NPE in handleUpdateTileEntity](http://pastebin.com/vVfQwZw2) due to the tile entity being null on my client.

This is happening around ~13 times a second (possibly multiple quantum storage units over at that area), spamming the log file to huge sizes, and causing insane memory usage on the Vanilla launcher which is trying to display the log.

Server is running v3.2.1 at the moment, but from looking at the recent commits and changelogs it doesn't seem to be fixed in a later version yet.

**Comment by gigabit101** [comment]
Will look into this after work

**Comment by modmuss50** [comment]
There is a a small chance I fixed this last night, https://github.com/gigabit101/QuantumStorage/commit/95ac320f10e483333bfaa43b43ee1d1fcf1079dd#diff-4e15bd029b6ae22935bced7d3ad59717R66

But I can take a look into the issue more if you want @gigabit101

**Comment by modmuss50** [comment]
It's an issue with reborncore tank syncing, I'm currently half way through writing a better syncing  system for it.
