### ISSUE TITLE
[1.10.2] [Bug] Item returned in creative

### ISSUE THREAD

**Issue by SnowShock35** [gigabit101/QuantumStorage#33]
### Important Information
- Minecraft 1.10.2
- Minecraft Forge 12.18.1.2094
- QuantumStorage 3.2.7
### Issue Description

When breaking the item in creative it drops. It shouldn't. It should be deleted from existence.

**Comment by gigabit101** [comment]
not a major issue but yeah I will fix for the next update

**Comment by K4N0** [comment]
How about only if it's empty. I forget, does it retain the items if broken?

**Comment by gigabit101** [comment]
Yea it dose

**Comment by SnowShock35** [comment]
@Badcholo Regardless if the tile has items or not it should just be deleted.

**Comment by K4N0** [comment]
I don't agree it should be deleted. Maybe it would be best to add a config option for that. I would hate for an admin to accidentally delete someones stuff. I actually think it's fine the way it is. How hard is it to delete 1 item from your inventory?

**Comment by modmuss50** [comment]
That is a good point, as at the moment it can be classed as a feature to prevent the loss of 1000's of items

**Comment by gigabit101** [comment]
It will be deleted if its empty that is as far as im going with this
