### ISSUE TITLE
[1.10.2] [Bug] Counting Error for Non-Stacking Items

### ISSUE THREAD

**Issue by SnowShock35** [gigabit101/QuantumStorage#34]
Hello,

I believe to have found a bug with QuantumStorage for Minecraft 1.10.2, here are the details. . .
### Important Information
- Minecraft 1.10.2
- Minecraft Forge 12.18.1.2094
- QuantumStorage 3.2.7
### Issue Description

With non stacking items like tools, weapons, armor, etc. The stack size increases from 1 to 65 as if there was an actual stack of items in there. After this it will continue to increment normally. 
### Issue Media

https://gfycat.com/GreatDisastrousKittiwake

**Comment by modmuss50** [comment]
Ah I know what's up, I think I broke it when I added the rounding to the rendering, should be an easy fix, i can take care of this if you want.

**Comment by gigabit101** [comment]
GG @modmuss50
