### ISSUE TITLE
Infinite items with Quantum Storage Unit (1.10.2)

### ISSUE THREAD

**Issue by Nachoboi** [gigabit101/QuantumStorage#40]
I found a bug while messing with the Storage Unit in the Hermitpack:
Duplication bug:
1.) Place a random stack able item in the storage unit (like 1 cobblestone).
2.) Place any item to dupe inside, it'll stack it behind the first item (say 1 block of diamond).
3.) Rapidly click while holding shift (or use a macro). And it'll pull the maximum amount of items that last item will stack with (so 64 for a block of diamond).

I noticed it states the maximum amount of the second item when you pull the first one out, so that seems to cause the dupe. Not sure on why it dupes non stack able items though... Hope i helped!

![2016-10-22_23 38 29](https://cloud.githubusercontent.com/assets/23007260/19623990/aa9830e2-98b0-11e6-932b-902ce1b9f993.png)

The screenshot is my sword duped a few times.

**Comment by Tiax** [comment]
I'm able to reproduce this. Shouldn't the input slot refuse any item not matching what's already in the storage, to begin with?

**Comment by gigabit101** [comment]
yeah I need to filter that slot easy fix
