### ISSUE TITLE
Client crash when opening Quantum Tank GUI

### ISSUE THREAD

**Issue by utoc** [gigabit101/QuantumStorage#42]
I suspect this is to do with TR's 2.0 update but I'll let you be the judge of that.  Oddly enough, no server crash.

Crash here: http://pastebin.com/FvrRT9dj

Running TR 2.0.0.80, RC 2.8.0.59 and QS 3.2.7 with FML 2109.

**Comment by gigabit101** [comment]
yup the class was moved in RebornCore this will be fixed in the next build

**Comment by modmuss50** [comment]
We are not ready to push the update, might be able to make QS work on both versions some how

**Comment by gigabit101** [comment]
Yeah I will put a copy of Slotfluid into QS for now
