### ISSUE TITLE
Only showing 64 items using screen with RFTools

### ISSUE THREAD

**Issue by cauliflower69** [gigabit101/QuantumStorage#43]
Using the latest build for 1.10.2 the screen and inventory module from RFTools only displays an amount of 64 items when used with any Quantum Storage block. 

Is there any way that it can display the correct amount?

Thanks

**Comment by gigabit101** [comment]
not unless RFTools uses the IDeepStorage api

**Comment by cauliflower69** [comment]
Thanks for the quick reply I will ask the RFTools dev

**Comment by McJty** [comment]
I'm wondering about this though. The storage drawers manage to give me the correct amount using IItemHandler by just returning itemstacks with > 64 items. Can't quantumstorage do the same? I mean storage drawers work fine with rftools (and The One Probe for that matter) without requiring any special support

**Comment by gigabit101** [comment]
QuantumStorage has a input and output slot that can be seen but the bulk storage is in a hidden slot that can not be piped to this is the same way Mfr used to do the dsu but I do use the IDeepStorage api from mfr for easy access to the Inventory contents, this api is also used but jabba for allowing ae2 to see its inventory correctly.
it should be real simple to add IDeepStorage compat for you

**Comment by modmuss50** [comment]
IDeepStorage should get a replacement at somepoint because thats from 1.7.10 MRF. But it does the job I guess

**Comment by gigabit101** [comment]
There is no point of charging it at this point as it is also used in refined storage now for issues just like this one

**Comment by gigabit101** [comment]
It uses a fake slot that is not acceptable
Using the item handler but using the mfr IDeepStorage api will allow it
work, I needed this in the past for AE now used for RS

**Comment by modmuss50** [comment]
@McJty: https://github.com/TechReborn/RebornCore/blob/1.10.2/src/main/java/powercrystals/minefactoryreloaded/api/IDeepStorageUnit.java
