### ISSUE TITLE
1.10.2 [Bug] right clicked quantum tank crash

### ISSUE THREAD

**Issue by Oharaicaine** [gigabit101/QuantumStorage#45]
right clicked a quantum fluid tank and got this crash.

http://pastebin.com/8dnZJPks

**Comment by TheDCPlaya** [comment]
Same crash here just placing and right clicking the tank crashed the client

**Comment by modmuss50** [comment]
https://github.com/gigabit101/QuantumStorage/blob/1.10.2/src/main/java/QuantumStorage/tile/TileQuantumTank.java#L137 Should be returning the tank no the tile I think.
