### ISSUE TITLE
Suggestion: have both quantum storage show an icon of the stored item.

### ISSUE THREAD

**Issue by Kaisoul** [gigabit101/QuantumStorage#46]
What i mean is that the tank shows the liquid type stored in the tank at a glance.
While the chest shows what item it's mass storing as an icon on it's top or front like storage drawers / mekanism bins.   
would make for a nice quality of life upgrade.

**Comment by modmuss50** [comment]
I had the idea of being able to put an item frame on the side, and then that automatically showing the item and the stored amount. 

It would cause some performance drops, but then its up to the player if they want to have it or not.

**Comment by gigabit101** [comment]
Yes it would be cool but I do and try to keep my mods as lag free as I and rendering a ItemStack on the tile takes up client tick time so if there is a bunch of them you will start getting fps drops eg StorageDrawers/jabba so I am not planing on adding this
