### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Sir-No** [gigabit101/QuantumStorage#48]
When you pull out items out of a quantum storage unit with a extremly fast method the item count in the storage unit will go into negative numbers. Tested both with glowstoned translocators and with ExtraUtils2 transfer nodes with 20 Speed Upgrades and 1 Stack Upgrade.

Reproducable setup with EU2 and enough Grid Power:  http://imgur.com/a/mQEPL

Minecraft: 1.10.2
Forge: 12.18.3.2185
QuantumStorage: 1.10.2-3.2.12
EU2: 1.10.2-1.1.3a

**Comment by gigabit101** [comment]
forgot to close this a while ago derp
