### ISSUE TITLE
Applied energistic storage bus not showing the contents of a quantum storage block correctly

### ISSUE THREAD

**Issue by jod126** [gigabit101/QuantumStorage#49]
I don't know if this is intentional or not but When you connect a storage bus from AE2 to a quantum stroage unit it will only read 1 stack of what is in the quantum storage usnit. example if there is 600 copper ingots in a quantum stoage unit and you use a stoage bus to read the contents of it, it will only show a stack of copper ingots in the terminal. https://drive.google.com/open?id=0BwMmBOk7-oipUzZKbmQwRDJhM2s gif to show issue.

Minecraft: 1.10.2
Forge: 2185
Applied energistic: rv4-alpha-9
Quantum storage: 3.2.12

**Comment by gigabit101** [comment]
I no its because they dont support the IDeepStorage Api any more so... Refined storage dose

**Comment by modmuss50** [comment]
Shit wrong button.

There is another issue about this.

**Comment by modmuss50** [comment]
I might look into finding another way to do this. I've got a few ideas

**Comment by Lupoid** [comment]
Guess I'll go back to storage drawers since both parties refuse to fix...

**Comment by gigabit101** [comment]
this cant be fixed in 1.10 without breaking current units It has been fixed in 1.11.2
