### ISSUE TITLE
AE2 reporting wrong number of items in a Quantum Storage.

### ISSUE THREAD

**Issue by Yabdat** [gigabit101/QuantumStorage#5]
If you connect a Quantum Storage via a Storage Bus to an ME system, no matter how many items in the Quantum Storage it will only show up as 65 in the ME system.

Tested with:
appliedenergistics2-rv2-stable-10
QuantumStorage-1.7.10-1.1.0
with Forge 10.13.4.1492 (newest) and Forge 10.13.4.1448 (recommended).

**Comment by gigabit101** [comment]
I am working on this as we speak

**Comment by gigabit101** [comment]
fixed in 1.2.0
