### ISSUE TITLE
QSU Blocks creating client side lag

### ISSUE THREAD

**Issue by Raffael7777** [gigabit101/QuantumStorage#51]
I am playing FTB presents Hermitpack 1.5.1 on a server, Minecraft Version 1.10.2, forge-12.18.3.2185.
It is using QuantumStorage-1.10.2-3.2.12.jar.

Any time I am in the vicinity of QSU blocks en masse (5-10+?), my client lags.  I do not drop in FPS.  I am not sure if it is causing a high bandwidth situation.  All I know is that I cannot open player based (bag) inventories, or interact with blocks while I am near them.  I can send chat messages to the server for others to see, but the client will not update the chat box with them for minutes.  At one point my client was 10k ticks behind the server.

Once I suspected it was the QSU block causing this issue, I tested this specifically by placing down 48 of them in a secluded chunk with no other mod items or blocks present.  The lag slowly developed into a situation where I could do nothing around them, and subsided when a friend broke them for me.

I believe another player has experienced this bug here: https://forum.feed-the-beast.com/threads/quantum-storage-unit-lag.208599/

I do not have any log files, but I will try to get some if you would like.  I will also have the server owner update to the latest version as well as all of the players, to see if the latest version has fixed this issue already.

Could this be caused by the QSU blocks not having a transparent block (air or other) above them?

**Comment by gigabit101** [comment]
Yup there is a new version that should fix this but you will have to wait till curse are back from holiday so they can approve the issue
