### ISSUE TITLE
[1.10.2] quantum storage will not count the first 64 items with Refined Storage

### ISSUE THREAD

**Issue by Protheus** [gigabit101/QuantumStorage#54]
**At refined Storage they informed me it is a Quantum Storage issue:**
https://github.com/raoulvdberge/refinedstorage/issues/858

Shot:
When you have <64 items in a QSU, RS will not display the items in its grid view.
When you have e.g. 66 items in a QSU, RS will display 2 items, the other 64 will not be counted but are there.

**Versions:**
MC: 1.10.2
Forge: 2202
QuantumStorage-1.10.2-3.2.17
Refinedstorage-1.2.16

**Comment by gigabit101** [comment]
fixed in next build

**Comment by Protheus** [comment]
Tnx
