### ISSUE TITLE
[Feature request] AE2 storage bus

### ISSUE THREAD

**Issue by Aphenon** [gigabit101/QuantumStorage#58]
Can you make it so the AE2 storage bus can see more than the one stack?

**Comment by ThomasAunvik** [comment]
> We decided to drop any support for special inventories in 1.10 because forge provides a common interface now for anyone to use (at least up to 2^31 per slot, like a dsu).
> 
> This results in longer having to add support for every storage mod out there to every mod interacting with storages. Now each storage mod can implement their own solution and everyone can use it. And it just works. For example storage drawers, there is no special support for it on our side.
> 
> Should a mod still insists on doing it as in 1.7.10 instead of adapting to 1.10, they certainly can expect other mods not supporting it when there is another solution which requires less work and provides more benefits.
-Yueh https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2550#issuecomment-257512457

**Comment by gigabit101** [comment]
I no and I dont care

**Comment by gigabit101** [comment]
In 1.11 its fixed I have moved over. 
I am not doing this in 1.10 as it will break all currently used storage units

**Comment by nimrod7137** [comment]
What a prick response lol

**Comment by modmuss50** [comment]
What gigabit is trying to say is it cannot be fixed without emptying current storage units. I dont think you want everyone to loose all their items.
