### ISSUE TITLE
Quantum Tank/Manual Bucketing crash

### ISSUE THREAD

**Issue by squillis** [gigabit101/QuantumStorage#59]
It's happened multiple times, I'm using a Quantum Tank to manually take water out with a bucket and this is the crash report I get and sometimes the internal GUI shows -1 of the fluid.
I just right click with the bucket in hand and it "shuts down server" message.
 
http://pastebin.com/j51y4BPi

Additionally, when using transfer nodes (fluid) from Extra Utilities 2 it corrupts the world and you have to delete the tank Via MC edit. (I don't have crash log for this although it happens 100% of the time. I don't want to corrupt another world.)

**Comment by gigabit101** [comment]
this crash is due to tinyprogressions as for the transfer node its extra utils side and has been reported months ago
