### ISSUE TITLE
duplication bug 

### ISSUE THREAD

**Issue by zed-hex** [gigabit101/QuantumStorage#63]
if any block from the mod is broken via a block breaker from any mod (tested with project red and actually additions ones) it will make 2 of the block.

**Comment by zed-hex** [comment]
this bug report also looks like it is caused via the same problem with the mod: https://github.com/gigabit101/QuantumStorage/issues/61

**Comment by RayzoRayy** [comment]
So your saying NotEnoughWands moving wand needs to be fixed ? So I can update the thread on his issue tracker and tell him to update the mod to provide a fix?
