### ISSUE TITLE
[1.11.2][Alpha1] java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer

### ISSUE THREAD

**Issue by addrever** [gigabit101/QuantumStorage#65]
Hello,

I am having a weird crash I believe related to quantum storage.  I have attached the log file.

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2259
QuantumStorage: Alpha1 ( 3.2.19 )
RebornCore: 2.13.5.42

[fml-server-latest.txt](https://github.com/gigabit101/QuantumStorage/files/853246/fml-server-latest.txt)
[latest.txt](https://github.com/gigabit101/QuantumStorage/files/853247/latest.txt)

Please let me know if you need further information.

Thank you!

**Comment by gigabit101** [comment]
fixed in alpha 2
