### ISSUE TITLE
[1.11.2][Alpha2] - net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from QuantumStorage (quantumstorage)

### ISSUE THREAD

**Issue by savosdarkran** [gigabit101/QuantumStorage#66]
Hello

Having a crash on the new version on a server installation.  The main error is java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen.

MC Version: 1.11.2
Forge: 13.20.0.2259
RebornCore: 2.13.5.42
Quantum Storage: alpha2

No other mods installed.  Just Reborn and QS.  Log files attached.

[fml-server-latest.txt](https://github.com/gigabit101/QuantumStorage/files/853677/fml-server-latest.txt)
[latest.txt](https://github.com/gigabit101/QuantumStorage/files/853678/latest.txt)

**Comment by gigabit101** [comment]
Crap missed a @side will fix tonight

**Comment by gigabit101** [comment]
fixed in alpha 3
