### ISSUE TITLE
in 1.11.2 It seems like the Render Special upgrade doesnt work

### ISSUE THREAD

**Issue by Lothrazar** [gigabit101/QuantumStorage#68]
If i click the upgrade on the storage unit, nothing happens.

If i click it on the barrel, i magically just get one more in my inventory every time i click, so i just get free infinite ones.

**Comment by gigabit101** [comment]
yup known bug fix coming soon redoing the render code as I have made improvements

**Comment by gigabit101** [comment]
fixed
