### ISSUE TITLE
[1.11.2] Crash wrong MC version

### ISSUE THREAD

**Issue by ThomasAunvik** [gigabit101/QuantumStorage#69]
I crashed after some time while playing on a server, and it said i had the wrong MC version of the mod. It said it was 1.10.2 version not 1.11.2, i have 1.11.2 version installed on the server and the client.

What is even weird is that it knows its location:
`Location: A:\Servers\AlotO'Mods\mods\QuantumStorage-1.10.2-3.3.0.jar`
But i dont find any mods in the server that has that version.
If i would send a location for the mod it would be this:
`A:\Servers\AlotO'Mods\mods\QuantumStorage-1.11.2-alpha3.jar`

Quantum Storage: 1.11.2-alpha3

[Crash Log](1.11.2-alpha3)

After i join the server, a second later the client crashes with a weird white background.

The crash i had just before this crash happened:
https://minecraft.curseforge.com/projects/solar-flux-reborn/issues/54
And the crash that happened just after this crash happened:
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/90

**Comment by gigabit101** [comment]
you are using the 1.10 build of QuantumStorage 3.3.0 is 1.10.2 not 1.11

**Comment by ThomasAunvik** [comment]
Ehm, as i said, i am not using the 1.10 build of the QuantumStorage. I am using 1.11.2-alpha3.

**Comment by gigabit101** [comment]
Then this is user error or a curse error I no this is not my side as 3.3.0 came out after alpha 3 so there is nothing I can do about this I am confused what has happened

**Comment by gigabit101** [comment]
Also no one else has reported this issue and I have the mod running on my own server so.. I'm leaving this as user error
