### ISSUE TITLE
Add lock feature

### ISSUE THREAD

**Issue by Protheus** [gigabit101/QuantumStorage#7]
Just like the Jabba barrel add a lock function to the chest so that when it is empty it remembers it content.

**Comment by gigabit101** [comment]
hmm maybe

**Comment by Protheus** [comment]
MFR DSU has it planned since last year... So if you implement it soon many will love it 😀

**Comment by Tbsc** [comment]
I might make it... Lol I kinda want something to do so yeah. :P

**Comment by gigabit101** [comment]
If you won't to PR it then go ahead but I'm on holiday atm so I can't do
much

**Comment by Tbsc** [comment]
I can't make git work as it's supposed to and it just doesn't launch, so yeah, I probably won't do it sadly.. I want to do it but yeah

**Comment by Protheus** [comment]
I suck at java... It seems the mfr dsu finsly has a similar feature... But they post it with a nrw cofh core that is not available so useless

**Comment by Tbsc** [comment]
No cofh core? The core lib is available for download online, in curseforge or teamcofh.com

**Comment by Protheus** [comment]
The one used for the new mfr is not available and skyboy is using that version for his alpha build and posting on curseforge but not usable

**Comment by gigabit101** [comment]
WIP
