### ISSUE TITLE
Inserting Forestry Saplings to QSU crashes client

### ISSUE THREAD

**Issue by ThomasAunvik** [gigabit101/QuantumStorage#70]
[Crash Log](https://hastebin.com/xugaqijuwi.php)
Quantum Storage Mod: 1.11.2-alpha3
Forestry 5.3.2.60

When i inserted a sapling from forestry into the QSU the client crashed, when trying to open the QSU it crashes again.
After exporting the item using a Item Transfer Node the client crashes after opening the GUI.
So, then i broke the Item Transfer Node, and i crashed... RIP client, and i think i can never join the server until i kill all the entities... unless i do /spawn other Thaun_

Is it a way to fix it?

Forestry Tree Farm with Quantum Storage Unit = Impossible
or i should say

Forestry Saplings in a QSU is not a good idea! I think that also applies for bees...

**Comment by ThomasAunvik** [comment]
Ugh, even doing `/kill @e[type=Item]` does not work... I crash when i come too close to the area of where i broke the Item Transfer Node
[Different Crash Log](https://hastebin.com/raw/zojuvucupa)

**Comment by ThomasAunvik** [comment]
Found a solution! At line 80 of the Different Crash log was to replace the block with air.
It would look like this:
`Entity's Block location: World: (-20795,65,-8081)`

**Comment by mezz** [comment]
It looks like QuantumStorage is stripping the NBT from the sapling, which leaves it in an illegal state.

**Comment by gigabit101** [comment]
fixed in 4.0.1
