### ISSUE TITLE
Invalid cast on getCapability call, missing check

### ISSUE THREAD

**Issue by BlayTheNinth** [gigabit101/QuantumStorage#71]
Causes crash for mods trying to `getCapability` on QuantumStorage blocks without `hasCapability`-ing first.

https://github.com/gigabit101/QuantumStorage/blob/1.11.2/src/main/java/QuantumStorage/rewrite/AdvancedTileEntity.java#L59-L63

`java.lang.ClassCastException: net.minecraftforge.items.ItemStackHandler cannot be cast to MyCoolCustomCapability`

**Comment by modmuss50** [comment]
That also needs the super call as well
