### ISSUE TITLE
Quantum Storage disappears when broken

### ISSUE THREAD

**Issue by Protheus** [gigabit101/QuantumStorage#73]
- When you place an empty QSU and break it with a pickaxe, the items disappears. just like breaking stone with your hand, the stone disappears.

- When you place a QSU with items in it and break it, it exist and you can pick it up.

QuantumStorage-1.10.2-3.3.1
Forge1.10.2-12.18.3.2254

**Comment by gigabit101** [comment]
yup I no what I did will fix tonight

**Comment by Protheus** [comment]
tnx man.

**Comment by gigabit101** [comment]
fixed in new build
