### ISSUE TITLE
Quantum Tank broken on 1.11.2

### ISSUE THREAD

**Issue by Seegras** [gigabit101/QuantumStorage#76]
It's not really possible to use the quantum tank in 1.11.2. It doesn't really want interface to pipes or fluid nodes from extrautils2, ender tanks from ender tanks and ender storage, fluid interfaces from refined storage and just about everything else I could find. 

But sometimes when connecting it somewhere it did get ore loose fluids quite arbitrarily.

**Comment by gigabit101** [comment]
fixed in 4.1.3
