### ISSUE TITLE
[1.10.2] Redstone Arsenal - Omniwrench - Not compatible with QuantumStorage

### ISSUE THREAD

**Issue by Hodel1** [gigabit101/QuantumStorage#79]
Hi,

i wish a support of Wrenches to dig up.
For example: The Omni-Wrench can't break the storage unit.

At first I thought it was the Wrench so i posted it at CoFH Teams Issuetracker.
[https://github.com/CoFH/Feedback/issues/178](url)

**Comment by gigabit101** [comment]
So I do not support any type of wrench as it requires me to use the api
This is not something I plan on adding just use a pickaxe
