### ISSUE TITLE
Items not stacking

### ISSUE THREAD

**Issue by Protheus** [gigabit101/QuantumStorage#8]
Using:
- QuantumStorage-1.7.10-1.4.0
  - RebornCore-1.0.0.8-universal

For some reason when using your new versions items don't stack in my inventory (http://imgur.com/Ws8OiJp) - when using v1.3.0 without the RebornCore they stack fine and no problem.

Not sure where the issue is

**Comment by gigabit101** [comment]
yup this is a problem I forgot about its something to do with my QuantumBag there will be a fix very soon

**Comment by gigabit101** [comment]
Fixed in build 1.7.10-1.4.1

**Comment by Protheus** [comment]
Sweet tnx
