### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by SFort** [gigabit101/QuantumStorage#80]
If you are interacting with a quantum storage while the block is broken you can still take out a stack.
QuantumStorage: 1.10.2-3.3.2
[Video](https://youtu.be/B27eT4Z0yNU)

**Comment by Sir-Will** [comment]
Was this not fixed? This still works in 1.10.2-3.3.4

**Comment by gigabit101** [comment]
1.10 has not been suported in a long time update to 1.11+ for fix
