### ISSUE TITLE
Items being deleted

### ISSUE THREAD

**Issue by mjcompgeek** [gigabit101/QuantumStorage#85]
Using FTB Beyond 1.8.1 that contains Quantum Storage v3.3.3.

Place items into a Quantum Storage Unit. Attempt to rotate with either Yeta wrench from Ender IO or Wrench from IC2 and all items get deleted.

Tested with multiple different items and placements. 

Lost a majority of items on our server when attempting to move the units around.

**Comment by gigabit101** [comment]
already fixed in 3.3.4
