### ISSUE TITLE
1.10.2 JEI Search Bug

### ISSUE THREAD

**Issue by MrSapient** [gigabit101/QuantumStorage#87]
Everytime i look your mod up in JEI i get this error in my server console.
https://pastebin.com/3V0RLqzv

QuantumStorage-1.10.2-3.3.4
jei_1.10.2-3.14.7.420
BrandonsCore-1.10.2-2.1.8.107-universal
extrautils2-1.10.2-1.4.4
Forge-12.18.3.2316

**Comment by gigabit101** [comment]
nothing in that log points to me

**Comment by MrSapient** [comment]
This only happens when I @ your mod in JEI no other mod

**Comment by modmuss50** [comment]
Looks a lot like Brandon's core, try removing that.
