### ISSUE TITLE
DSU loses items when broken

### ISSUE THREAD

**Issue by Protheus** [gigabit101/QuantumStorage#9]
Using:
- QuantumStorage-1.7.10-1.4.1
- RebornCore-1.0.0.8-universal

Items in a storage unit are gone when you break them ... not good :(

**Comment by gigabit101** [comment]
o0

**Comment by gigabit101** [comment]
this is why beta I seem to break things is large updates ;)

**Comment by gigabit101** [comment]
umm there is a new sync issue but when broke and replaced the items are there

**Comment by gigabit101** [comment]
What did u break it with ??

**Comment by Protheus** [comment]
heheh...seems I'm often here - Hope I get some dental care insurance :-)

Atomic disassembler from mekanism, my hand, crescent wrench (TE) and a Actually Additions drill

**Comment by gigabit101** [comment]
I cant seem to do this on my end are u on a server or ssp??

**Comment by Protheus** [comment]
ssp

**Comment by gigabit101** [comment]
can u test a debug version for me ??

**Comment by Protheus** [comment]
sure

**Comment by gigabit101** [comment]
try this it will tell me what is dropping in the console when u break the block https://www.dropbox.com/s/bzf6x8cpylwey0t/QuantumStorage-1.7.10-1.4.2.jar?dl=0

**Comment by gigabit101** [comment]
also fixed sync issue

**Comment by Protheus** [comment]
oke trying now - brb :)

**Comment by gigabit101** [comment]
kk

**Comment by gigabit101** [comment]
test on the mk1 that's the one with debug code

**Comment by Protheus** [comment]
not working. But now I see <ERROR> in Waila (http://imgur.com/7cfPiXG) - Items are gone when the unit are placed back

**Comment by Protheus** [comment]
[18:15:23] [Client thread/WARN] [Waila]: QuantumStorage.compat.waila.WailaProviderMachines.getWailaBody:27
[18:15:23] [Client thread/WARN] [Waila]: Catched unhandled exception : [class QuantumStorage.compat.waila.WailaProviderMachines] java.lang.ClassCastException: QuantumStorage.block.tile.TileQuantumDsuMk1 cannot be cast to QuantumStorage.block.tile.TileQuantumDsuMk2

**Comment by gigabit101** [comment]
use a mk1

**Comment by Protheus** [comment]
same

**Comment by gigabit101** [comment]
as for waila I was messing with that when u gave me with this bug

**Comment by gigabit101** [comment]
so there is now nothing in the QSU ??

**Comment by Protheus** [comment]
I place 6 seeds, break and replace and gone

**Comment by gigabit101** [comment]
o0 I see try more than a stack

**Comment by Protheus** [comment]
yes that works PERFECT :-).. and wailia is showing at the top also what the content is and the total amount :-)  sweet :+1:

**Comment by gigabit101** [comment]
ok I know what's going on

**Comment by Protheus** [comment]
But when the QSU is in the inventory the total amount is not correct. I placed 160 in the storage and it tells me 96 are in - but when placed down the correct amount is displayed

**Comment by Protheus** [comment]
dinner time - will play some more later on but tnx for the progress... this mod is perfect :+1:

**Comment by gigabit101** [comment]
that's sync issue

**Comment by Protheus** [comment]
thank you :-) now work on teh upgrade so I can upgrade my QSU to a higher tier and keeping the content in each :-)

**Comment by gigabit101** [comment]
o0 I didn't think of that hmm
