### ISSUE TITLE
[1.11.2] Quantum Barrel does not display items and only faces West.

### ISSUE THREAD

**Issue by Andronomos** [gigabit101/QuantumStorage#90]
I'm using QuantumStorage-1.11.2-4.2.2 on Forge 1.11.2-13.20.0.2315. 

Whenever I place a Quantum barrel it always faces West no matter which direction I'm facing when I place it. Also, the "screen" on the barrel never displays what's inside the barrel, it's always blank.

**Comment by ExDomino** [comment]
Still not fixed in 1.12 ? : QuantumStorage 4.3.4.
Work for blocks, not for items, and The One Probe cannot see how many items are on it.

**Comment by gigabit101** [comment]
this is on my todo

**Comment by Andronomos** [comment]
The directional placement seems to be fixed in the latest 1.11.2 release but I don't think the display is.

**Comment by ExDomino** [comment]
QuantumStorage 4.3.5, still not fixed.

**Comment by ouroborus** [comment]
The display works with items that have 3D icons but not with items that have 2D icons. I suspect the icon is there, just buried in the model.

**Comment by ouroborus** [comment]
Given the positioning of the 3D icons, it feels like there's supposed to be a count showing above the icon as well. I believe the icons either need to be centered in the display area or show a count.

**Comment by gigabit101** [comment]
The barrels will be being removed as of next version as I dont like the feel of them in this mod,
I will be leaving them in and for now I have removed the recipe
