### ISSUE TITLE
[1.11.2] Quantum Storage Disk - No Recipe?

### ISSUE THREAD

**Issue by brisingraerowing** [gigabit101/QuantumStorage#91]
Is there supposed to be a recipe for the Quantum Storage Disk? JEI doesn't show one.

**Comment by TheSnowyChickens** [comment]
Hello (At first ,my English is not so good :) )

A question : JEI only don't show the recipe or the whole Item?
Because in my modpack this Item don't exist , (Refined and Quantum are installed) in both ,creative inv. and JEI.

Thx

MC : 1.12
Newest Forge
Newest Quantum Storage and Refined

**Comment by brisingraerowing** [comment]
Which Minecraft version? The item was added for 1.11(.2?).

**Comment by gigabit101** [comment]
1.11.2

**Comment by gigabit101** [comment]
fixed in 1.12 1.11 on todo list
