### ISSUE TITLE
[1.12] - Quantum trash Can - option to enable/disable

### ISSUE THREAD

**Issue by Protheus** [gigabit101/QuantumStorage#93]
If possible, an option to have the trash can disabled/enabled in the config. I dont see an option in the config.

Yours and ExU2 trash can have the same recipe.

File: QuantumStorage-1.12-4.3.4
Forge: 2405

**Comment by gigabit101** [comment]
fixed in dev

**Comment by Protheus** [comment]
perfect, tnx
