### ISSUE TITLE
Slight read errors with storage and name of reinforced chests

### ISSUE THREAD

**Issue by PBGgamer** [gigabit101/QuantumStorage#94]
Hey, I love this mod, it's super useful! But I found a bug with ver. 4.3.4, where if anything in the chest is under a stack, e.g. 60 coal, and you try to shift click more than 4 coal in, you lose the excess as it doesn't start a new stack. Also, it seems like the chest code is rewritten each time it's broken, because I gave it a new name via the anvil for ease of use, but it was reset to the original name when broken. Hope you can fix these, gigabit101!

**Comment by Trinsec** [comment]
I've noticed this as well. If I have 10 iron, and I shift-click a full stack in it, the 10 becomes 64 and the rest is gone. It's a bit annoying. Happens with 1.12-4.4.0 in the All The Mods 3 pack.
