### ISSUE TITLE
|1.12| losing content

### ISSUE THREAD

**Issue by Bass2style** [gigabit101/QuantumStorage#97]
QSU are losing content when you broke multiple QSU at the same time on FTB Unstable.
it seems to affect the QSU that whas not focused.

version of Unstable : 1.0.6
version of the mod : 4.3.5

reproductible : yes.
on server : nope, local gameplay, untested on server

demo (traitment by YT actually, should be ready rapidely. xD) : https://www.youtube.com/watch?v=Hr1ayfY8ru0

**Comment by gigabit101** [comment]
fixed in new build

**Comment by Bass2style** [comment]
thanks for your quick reaction and quick fix.
