### ISSUE TITLE
Quantum crafter consumes all stars after completion

### ISSUE THREAD

**Issue by Vectrobe** [gigabit101/QuantumStorage#98]
The quantum crafter, upon completion will consume the entire stack of stars, instead of only one.

- you have to reset the counter to 0 on the same tick you destroy a star, or it'll loop
- you have to decrement the stack by one if the stack contains more than one, otherwise you can then destroy the stack

the behaviour suggests the problem is in the later note...

**Comment by Vectrobe** [comment]
github seems to be going AWOL atm so I cant really check the code...

**Comment by gigabit101** [comment]
fixed in dev
