### ISSUE TITLE
[1.12] Quantum Storage Unit - 0% Full, can't insert next item of the same type

### ISSUE THREAD

**Issue by Krosta8** [gigabit101/QuantumStorage#99]
Hello,
I have a problem with Quantum Storage Unit. I automatically insert items thought AE2 and on randomly count it stopped "eating" another stack.
I tried to restart server, but this is not a problem. All chunks are loaded permanently with Chunkloader from ChickenChunks.
Do you know, how to fix that?
PS: Not all of QSU have this problem and there is not any error in server-log

Forge: forge1.12-14.21.1.2443
QuantumStorage: QuantumStorage-1.12-4.4.0
AppliedEnergistics: appliedenergistics2-rv5-alpha-2
Images: http://imgur.com/a/sOxbc

**Comment by gigabit101** [comment]
Can you try a break and replace it will store its inv so it will be fine

**Comment by Krosta8** [comment]
Already tried, it didn't help. Still the same problem. I tried to put the top stack out and then in, but without any solution.

**Comment by gigabit101** [comment]
I will take a look into this 2day might have to send you a debug build to find out wtf is going on
